Repository prebid/prebid.github.io, pull requests merged in 2018-06, with the labels that each got.

#771 Updated docs to reflect GDPR support
  dev-docs/bidders/unruly.md
Labels: LGTM, not merged yet

#821 Create andbeyond.md
  dev-docs/bidders/andbeyond.md
Labels: LGTM

#734 Update cox.md
  dev-docs/bidders/cox.md
Labels: LGTM, Pending PBJS Release

#754 doc(adyoulike): add flat to gdpr support
  dev-docs/bidders/adyoulike.md
Labels: LGTM, not merged yet

#803 Widespace GDPR support variable
  dev-docs/bidders/widespace.md
Labels: LGTM

#807 gdpr_supported: true for rtbhouse adapter
  dev-docs/bidders/rtbhouse.md
Labels: LGTM

#809 API Reference: Adding additional info on onEvent handlers, and PBS timeout
  dev-docs/publisher-api-reference.md
Labels: LGTM

#810 Add GDPR support variable to madvertise bidder adapter doc
  dev-docs/bidders/madvertise.md
Labels: LGTM

#838 add gdpr support in freewheel bidder adapter
  dev-docs/bidders/freewheel.md
Labels: LGTM

#421 Docs for AdSpirit bid adapter
  dev-docs/bidders/adspirit.md
Labels: LGTM, Pending PBJS Release, not merged yet

#765 Troubleshooting debugging
  _layouts/example.html
  dev-docs/common-issues.md
  dev-docs/prebid-troubleshooting-guide.md
  dev-docs/toubleshooting-tips.md
  dev-docs/troubleshooting-tips.md
Labels: LGTM

#768 gdpr enabled in https://github.com/erolosty/Prebid.js/commit/4196b9f6…
  dev-docs/bidders/quantcast.md
Labels: LGTM

#770 xaxis bidder documentation updated for 1.x/gdpr adapter update
  dev-docs/bidders/xaxis.md
Labels: LGTM

#800 in-app support added to kumma adapter
  dev-docs/bidders/kumma.md
Labels: LGTM

#827 add docs for pgxyz
  dev-docs/bidders/playgroundxyz.md
Labels: needs work

#828 New optional bid parameter
  dev-docs/bidders/nanointeractive.md
Labels: LGTM

#830 Fyber Prebid Adapter Documentation
  dev-docs/bidders/fyber.md
Labels: LGTM

#832 added gdpr_supported variable
  dev-docs/bidders/adxcg.md
Labels: LGTM

#834 add notes on handling pbs only bidders
  dev-docs/get-started-with-prebid-server.md
Labels: LGTM

#839 Added GDPR consent management to YOC VIS.X Bid Adapter
  dev-docs/bidders/visx.md
Labels: LGTM, not merged yet

#852 Change 'Gamoshi Gambid' to simply Gamoshi
  dev-docs/bidders/gambid.md
Labels: LGTM
