Repository prebid/prebid.github.io, pull requests merged in 2018-05, with the labels that each got.

#735 PulsePoint Bidder GDPR support
  dev-docs/bidders/pulsepoint.md
Labels: LGTM, Pending PBJS Release

#719 Rubicon bidders page: Update for GDPR support
  dev-docs/bidders/rubicon.md
Labels: LGTM, Pending PBJS Release

#729 update adform bidders page for GDPR support
  dev-docs/bidders/adform.md
Labels: Pending PBJS Release

#714 Adding dgads bidder dev docs
  dev-docs/bidders/dgads.md
Labels: Pending PBJS Release, needs work

#710 Documentation added for yuktamedia analytics
  overview/analytics.md
Labels: needs work

#696 Create rtbdemandadk.md
  dev-docs/bidders/rtbdemandadk.md
Labels: needs work

#721 Create docs for Nano Interactive Bid Adapter
  dev-docs/bidders/nanointeractive.md
  index.md
Labels: needs work

#703 Adding Consumable bidder dev docs
  dev-docs/bidders/consumable.md
Labels: not merged yet

#737 Add GDPR support to Beachfront doc
  dev-docs/bidders/beachfront.md
Labels: LGTM, Pending PBJS Release

#738 Add LockerDome bidder docs
  dev-docs/bidders/lockerdome.md
Labels: LGTM, Pending PBJS Release

#748 Updated docs for Index Exchange's Prebid 1.0 adapter + GDPR support
  _includes/send-all-bids-keyword-targeting.md
  adops/deals.md
  dev-docs/bidders/indexExchange.md
  dev-docs/publisher-api-reference.md
Labels: LGTM, Pending PBJS Release

#746 Added GDPR support to A4G Bid Adapter
  dev-docs/bidders/a4g.md
Labels: LGTM, Pending PBJS Release

#749 added latLong documentation for rubicon
  dev-docs/bidders/rubicon.md
Labels: LGTM

#782 Add Sharethrough GDPR compliance info
  dev-docs/bidders/sharethrough.md
Labels: LGTM, not merged yet

#772 Update TrustX doc file to support gdpr
  dev-docs/bidders/trustx.md
Labels: LGTM, not merged yet

#750 GDPR support for Aardvark
  dev-docs/bidders/aardvark.md
Labels: LGTM, not merged yet
