Repository prebid/prebid.github.io, pull requests merged in 2018-03, with the labels that each got.

#619 Update Orbitsoft module dev-doc
  dev-docs/bidders/orbitsoft.md
Labels: Pending PBJS Release

#626 updateAdGenerationDocs
  dev-docs/bidders.md
Labels: LGTM

#627 Smart Name change
  dev-docs/bidders/smartadserver.md
Labels: LGTM

#642 fixed type of slave_id param
  dev-docs/bidders/adocean.md
Labels: LGTM

#572 Quantum Adapter Dev docs
  dev-docs/bidders/quantum.md
Labels: Pending PBJS Release

#600 Update beachfront doc
  dev-docs/bidders/beachfront.md
Labels: LGTM, Pending PBJS Release

#608 Add doc for FairTrade Bidder Adapter
  dev-docs/bidders/fairtrade.md
Labels: Pending PBJS Release

#616 Vertozbid Adapter: doc update for prebid 1.0
  dev-docs/bidders/vertoz.md
Labels: Pending PBJS Release

#624 Docs from adapter SmartyAds 1.x
  dev-docs/bidders/smartyads.md
Labels: LGTM, Pending PBJS Release

#630 Innity Adapter Documentation Support for Prebid.js 1.0
  dev-docs/bidders/innity.md
Labels: LGTM, Pending PBJS Release

#631 Rename doc file for DAN Marketplace Bid Adapter into danmarket.md
  dev-docs/bidders/danmarket.md
Labels: LGTM, Pending PBJS Release

#632 Add RTB House adapter docs
  dev-docs/bidders/rtbhouse.md
Labels: Pending PBJS Release

#633 Update AdyoulikeAdapter Doc
  dev-docs/bidders/adyoulike.md
Labels: LGTM, Pending PBJS Release

#672 Mod: chagne example on vuble doc
  dev-docs/bidders/vuble.md
Labels: LGTM

#669 Update vertamedia.md
  dev-docs/bidders/vertamedia.md
Labels: LGTM

#651 Update Yieldlab params with new naming
  dev-docs/bidders/yieldlab.md
Labels: LGTM

#638 Invibes Adapter - documentation
  dev-docs/bidders/invibes.md
Labels: LGTM, Pending PBJS Release

#670 New Content Ignite docs
  dev-docs/bidders/contentignite.md
Labels: LGTM, Pending PBJS Release

#671 Add doc for Oneplanetonly Bid Adapter
  dev-docs/bidders/oneplanetonly.md
Labels: LGTM, Pending PBJS Release

#653 Lifestreet Adapter: doc update for prebid 1.0
  dev-docs/bidders/lifestreet.md
Labels: LGTM, Pending PBJS Release
