Repository prebid/prebid.github.io, pull requests merged in 2018-02, with the labels that each got.

#577 updates to JSFiddle examples for multiformat updates
  dev-docs/examples/adjust-price.md
  dev-docs/examples/adunit-refresh.md
  dev-docs/examples/basic-example.md
  dev-docs/examples/brightcove-example.md
  dev-docs/examples/custom-price-bucket-using-setpricegranularity.md
  dev-docs/examples/custom-price-bucket.md
  dev-docs/examples/full-page-refresh.md
  dev-docs/examples/jw-cloud-example.md
  dev-docs/examples/jw-selfhost-example.md
  dev-docs/examples/kaltura-example.md
  dev-docs/examples/ooyala-example.md
  dev-docs/examples/outstream-video-example.md
  dev-docs/examples/send-all-bids.md
  dev-docs/examples/simplified-price-bucket-setup.md
  dev-docs/examples/size-mapping.md
  dev-docs/examples/use-prebid-with-appnexus-ad-server.md
  dev-docs/examples/videojs-example.md
  dev-docs/getting-started.md
  examples/adunit_refresh_example.html
Labels: LGTM

#550 add peak226 adapter
  dev-docs/bidders/peak226.md
  index.md
Labels: LGTM, Pending PBJS Release

#566 Xendiz bid adaptor docs
  dev-docs/bidders/xendiz.md
Labels: LGTM, Pending PBJS Release

#571 Add Yieldlab adapter docs to website
  dev-docs/bidders/yieldlab.md
Labels: LGTM, Pending PBJS Release

#575 Add adgeneration docs
  dev-docs/bidders/adgeneration.md
Labels: LGTM, Pending PBJS Release

#578 Update C1X Adapter docs
  dev-docs/bidders/c1x.md
Labels: LGTM, Pending PBJS Release

#585 Add doc for DAN_Marketplace Adapter
  dev-docs/bidders/danmarketplace.md
Labels: Pending PBJS Release

#589 Update Sonobi Bidder Adapter Documentation
  dev-docs/bidders/sonobi.md
Labels: Pending PBJS Release

#579 added information on new s2sConfig option
  dev-docs/bidders/prebidServer.md
  dev-docs/get-started-with-prebid-server.md
  dev-docs/publisher-api-reference.md
Labels: LGTM, Pending PBJS Release

#583 add: docs for Gamma adapter
  dev-docs/bidders/gamma.md
Labels: Pending PBJS Release
