Repository prebid/prebid.github.io, pull requests merged in 2018-07, with the labels that each got.

#831 Docs Weborama Adapter
  dev-docs/bidders/weborama.md
Labels: LGTM, not merged yet

#836 Add instream video and native support for ucfunnel adapter
  dev-docs/bidders/ucfunnel.md
Labels: LGTM, not merged yet

#851 Add gdpr support and key-value targeting to the Yieldlab bidder
  dev-docs/bidders/yieldlab.md
Labels: LGTM, not merged yet

#855 Create my6sense.md
  dev-docs/bidders/my6sense.md
Labels: LGTM, not merged yet

#856 Created polymorph.md for Polymorph Adapter
  dev-docs/bidders/polymorph.md
Labels: LGTM, not merged yet

#860 Document the new timedOut parameter for bidsBackHandler
  dev-docs/publisher-api-reference.md
Labels: Pending PBJS Release

#862 remove references to library type as an analytics adapter
  dev-docs/integrate-with-the-prebid-analytics-api.md
Labels: LGTM, not merged yet

#863 Update documentation for Sharethrough
  dev-docs/bidders/sharethrough.md
Labels: LGTM, not merged yet

#868 Update documentation for IX Adapter
  dev-docs/bidders/indexExchange.md
Labels: LGTM, Pending PBJS Release

#870 Update platformio.md
  dev-docs/bidders/platformio.md
Labels: LGTM, not merged yet

#873 gdpr supported - kumma
  dev-docs/bidders/kumma.md
Labels: LGTM, not merged yet

#881 Update vidazoo.md
  dev-docs/bidders/vidazoo.md
Labels: LGTM, not merged yet

#889 UOL - bidAdapter release candidate docs
  dev-docs/bidders/uol.md
Labels: LGTM, not merged yet

#899 Added doc for ZEDO
  dev-docs/bidders/zedo.md
Labels: LGTM, not merged yet
