Repository prebid/prebid.github.io, pull requests merged in 2019-04, with the labels that each got.

#1220 Bidphysics Bid Adapter dev-docs
  dev-docs/bidders/bidphysics.md
Labels: LGTM

#1165 SmartRTB doc file
  dev-docs/bidders/smartrtb.md
Labels: LGTM

#1225 pub API: added requestBids.auctionId
  dev-docs/publisher-api-reference.md
Labels: not merged yet

#1239 Added gdpr support
  dev-docs/bidders/telaria.md
Labels: LGTM

#1242 Update Cedato adapter bid params
  dev-docs/bidders/cedato.md
Labels: LGTM

#1255 Create stv.md
  dev-docs/bidders/stv.md
Labels: LGTM

#1265 add sortable to analytics.md and download.md
  download.md
  overview/analytics.md
Labels: LGTM

#1253 ShowHeroes Adapter dev-docs
  dev-docs/bidders/showheroes.md
Labels: LGTM, not merged yet

#1262 Submit NAF Digital adapter doc
  dev-docs/bidders/nafdigital.md
Labels: LGTM, not merged yet

#1236 Synacormedia: Added video parameters to documentaion.
  dev-docs/bidders/synacormedia.md
Labels: LGTM

#1217 PubCommonId - Add support for local storage
  dev-docs/modules/pubCommonId.md
Labels: LGTM

#1252 adding video to supported mediatypes
  dev-docs/bidders/emx_digital.md
Labels: LGTM

#1258 Updated Sonobi Docs to add userId support for unifiedId/tradedesk
  dev-docs/bidders/sonobi.md
Labels: LGTM

#1271 go2net docs
  dev-docs/bidders/go2net.md
Labels: LGTM
