Repository prebid/prebid.github.io, pull requests merged in 2019-03, with the labels that each got.

#1134 Cleanmedianet: New bidder adapter
  dev-docs/bidders/cleanmedianet.md
Labels: LGTM

#1137 New Adapter VMG
  dev-docs/bidders/vmg.md
Labels: LGTM, not merged yet

#1138 update removeAdUnit
  dev-docs/publisher-api-reference-old.md
  dev-docs/publisher-api-reference.md
Labels: LGTM

#1142 New bid adapter for OPEN8 doc
  dev-docs/bidders/open8.md
Labels: LGTM

#1149 Video support in Grid doc file
  dev-docs/bidders/grid.md
Labels: LGTM

#1150 New bid adapter for TheAdx doc
  dev-docs/bidders/theadx.md
Labels: LGTM, not merged yet

#1178 Add External Id to the Yieldlab Bidder Doc
  dev-docs/bidders/yieldlab.md
Labels: LGTM, not merged yet

#1176 New Adapter LoopMe
  dev-docs/bidders/loopme.md
Labels: LGTM, Pending PBJS Release

#1159 New Adapter MicroAd
  dev-docs/bidders/microad.md
Labels: LGTM, Pending PBJS Release

#1177 Submit Readme for Advangelists Bidder's Prebid Adapter
  dev-docs/bidders/advangelists.md
Labels: LGTM, not merged yet

#1186 Submit Brightcom Bidder Adaptor doc
  dev-docs/bidders/brightcom.md
Labels: LGTM, not merged yet

#1180 Add SmileWanted bidder documentation
  dev-docs/bidders/smilewanted.md
Labels: LGTM, not merged yet

#1179 New adapter myTarget
  dev-docs/bidders/mytarget.md
Labels: LGTM, not merged yet

#1126 update AJA adaptor: support native format
  dev-docs/bidders/aja.md
Labels: LGTM, not merged yet

#1204 Update TrustX doc file
  dev-docs/bidders/trustx.md
Labels: LGTM

#1215 Create cedato.md
  dev-docs/bidders/cedato.md
Labels: LGTM, not merged yet

#1219 Adpone Bid Adapter dev-docs
  dev-docs/bidders/adpone.md
Labels: LGTM

#1209 Add adman dev doc
  dev-docs/bidders/adman.md
Labels: LGTM

#1205 Create reklamstore.md
  dev-docs/bidders/reklamstore.md
Labels: LGTM

#1216 update s2s config params
  dev-docs/publisher-api-reference.md
Labels: LGTM

#1066 Update adikteev adapter (main PR now merged)
  dev-docs/bidders/adikteev.md
Labels: LGTM

#1223 Added MediaFuse Lift dev-docs
  dev-docs/bidders/mediafuseLift.md
Labels: LGTM

#1211 Improve Digital adapter: Adding usePrebidSizes param
  dev-docs/bidders/improvedigital.md
Labels: LGTM

#1218 Synacormedia: add post & bidfloor to documentation
  dev-docs/bidders/synacormedia.md
Labels: LGTM

#1227 orbidder: add bidfloor to documentation
  dev-docs/bidders/orbidder.md
Labels: LGTM
