Repository prebid/prebid.github.io, pull requests merged in 2019-01, with the labels that each got.

#1077 Add iframes at the bottom of the html tag
  dev-docs/publisher-api-reference-old.md
  dev-docs/publisher-api-reference.md
Labels: LGTM, not merged yet

#1062 New adapter "Coinzilla" added
  dev-docs/bidders/coinzilla.md
Labels: LGTM, not merged yet

#1067 Improve Digital adapter: Support for native ads & single request
  dev-docs/bidders/improvedigital.md
Labels: LGTM, not merged yet

#1075 Added new setConfig option for pbs adapterOptions
  dev-docs/bidders/prebidServer.md
  dev-docs/publisher-api-reference.md
Labels: LGTM, Pending PBJS Release

#1046 Advenue prebid adapter doc added
  dev-docs/bidders/advenue.md
Labels: LGTM, Pending PBJS Release

#1069 added new setConfig option, useBidCache
  dev-docs/publisher-api-reference.md
Labels: LGTM, Pending PBJS Release

#1084 added ozone adapter docs
  dev-docs/bidders/ozone.md
Labels: LGTM
