Repository prebid/prebid.github.io, pull requests merged in 2019-10, with the labels that each got.

#1495 Added doc file for Turk Telekom Bid Adapter
  dev-docs/bidders/turktelekom.md
Labels: LGTM

#1461 Outcon Bid Adapter
  dev-docs/bidders/outcon.md
Labels: LGTM

#1482 Create djax.md
  dev-docs/bidders/djax.md
Labels: LGTM

#1506 videonow Bid adapter's doc
  dev-docs/bidders/videonow.md
Labels: LGTM

#1459 add documentation for auctionDelay in userSync
  dev-docs/publisher-api-reference.md
Labels: LGTM

#1501 Update adastamedia.md
  dev-docs/bidders/adastaMedia.md
Labels: LGTM

#1540 Updating ozone docs
  dev-docs/bidders/ozone.md
Labels: LGTM

#1547 added LiveIntent in supported sub-module list
  dev-docs/bidders/pubmatic.md
Labels: LGTM

#1543 Update smartrtb docs
  dev-docs/bidders/smartrtb.md
Labels: LGTM

#1538 Improve Digital schain support
  dev-docs/bidders/improvedigital.md
Labels: LGTM

#1493 Liveintent user module docs added.
  dev-docs/modules/userId.md
Labels: LGTM

#1529 Add Parrable ID submodule docs
  dev-docs/modules/userId.md
Labels: not merged yet

#1550 Improve Digital adapter: video support
  dev-docs/bidders/improvedigital.md
Labels: LGTM, Pending PBJS Release

#1551 Gamoshi: Add support for userIds
  dev-docs/bidders/gamoshi.md
Labels: LGTM, Pending PBJS Release

#1554 PubMatic to support Parrable User Id sub-module
  dev-docs/bidders/pubmatic.md
Labels: LGTM, Pending PBJS Release

#1557 PubMatic coppa support update
  dev-docs/bidders/pubmatic.md
Labels: LGTM, Pending PBJS Release

#1513 Update doc for Yieldone Analytics Adapter
  download.md
  overview/analytics.md
Labels: LGTM

#1533 Sharethrough: Schain bidfloor adapter docs update
  dev-docs/bidders/sharethrough.md
Labels: LGTM

#1542 Create waardex alias for adkernel
  dev-docs/bidders/waardex
Labels: LGTM

#1536 Added Vrtcal Adapter Doc
  dev-docs/bidders/vrtcal.md
Labels: LGTM
