Repository prebid/prebid.github.io, pull requests merged in 2019-06, with the labels that each got.

#1329 added hbPb macro replacement to the example creative templates
  adops/send-all-bids-adops.md
  adops/setting-up-prebid-for-amp-in-dfp.md
  adops/setting-up-prebid-with-the-appnexus-ad-server.md
  adops/step-by-step.md
  dev-docs/show-prebid-ads-on-amp-pages.md
  prebid-mobile/adops-line-item-setup-dfp.md
  prebid-mobile/adops-line-item-setup-mopub.md
Labels: LGTM, not merged yet

#1198 [Docs][PrebidServer] Adding `/version` doc
  prebid-server/endpoints/version.md
Labels: LGTM, not merged yet

#822 Added docs for #2562
  dev-docs/publisher-api-reference.md
Labels: help wanted, needs work

#1308 Update Sharethrough documentation
  dev-docs/bidders/sharethrough.md
Labels: question

#1351 Added documentation for configuration option rdn.endpoint
  dev-docs/bidders/rdn.md
Labels: LGTM, Pending PBJS Release

#1350 adds bidFloor param and userId to variables for yieldmo module
  dev-docs/bidders/yieldmo.md
Labels: LGTM

#1347 Add appier analytics adapter doc info to analytics page
  download.md
  overview/analytics.md
Labels: LGTM

#1340 update and rename NextMillennium
  dev-docs/bidders/nextMillennium.md
Labels: LGTM, Pending PBJS Release

#1338 Add SlimCut bid adapter
  dev-docs/bidders/slimcut.md
Labels: LGTM

#1334 Add player params to beachfront doc
  dev-docs/bidders/beachfront.md
Labels: LGTM

#1346 added FeedAd adapter parameters
  dev-docs/bidders/feedad.md
Labels: LGTM

#1322 PLEASE MERGE -> Adding Scaleable Analytics to download/overview markdown files
  download.md
  overview/analytics.md
Labels: LGTM, not merged yet

#1328 (New adapter) Added bidglass dev-doc
  dev-docs/bidders/bidglass.md
Labels: LGTM

#1363 ID5 ID user id module docs
  dev-docs/modules/index.md
  dev-docs/modules/userId.md
Labels: LGTM

#1358 Updated documentation for video adapter support.
  dev-docs/bidders/indexExchange.md
Labels: LGTM
