Repository prebid/prebid.github.io, pull requests merged in 2019-09, with the labels that each got.

#1463 Supply Chain Object Module docs
  _data/sidebar.yml
  dev-docs/bidders/pubmatic.md
  dev-docs/modules/index.md
  dev-docs/modules/schain.md
Labels: LGTM

#1416 Nobid Prebid Adapter documentation commit
  dev-docs/bidders/nobidBidAdapter.md
Labels: LGTM

#1444 Improve Digital adapter: adding bid floor price
  dev-docs/bidders/improvedigital.md
Labels: LGTM

#1445 Optimera Bid Adapter device param update.
  dev-docs/bidders/optimera.md
Labels: LGTM

#1465 Sdk 1 2 release
  _data/sidebar.yml
  prebid-mobile/pbm-api/android/code-integration-android.md
  prebid-mobile/pbm-api/android/pbm-adunit-android.md
  prebid-mobile/pbm-api/android/pbm-api-android.md
  prebid-mobile/pbm-api/android/pbm-interstitialadunit-android.md
  prebid-mobile/pbm-api/android/pbm-targeting-params-android.md
  prebid-mobile/pbm-api/android/pbm-util-android.md
  prebid-mobile/pbm-api/android/prebidmobile-object-android.md
  prebid-mobile/pbm-api/ios/code-integration-ios.md
  prebid-mobile/pbm-api/ios/pbm-adunit-ios.md
  prebid-mobile/pbm-api/ios/pbm-interstitialadunit-ios.md
  prebid-mobile/pbm-api/ios/pbm-targeting-ios.md
  prebid-mobile/pbm-api/ios/pbm-util-ios.md
  prebid-mobile/pbm-api/ios/prebidmobile-object-ios.md
Labels: not merged yet

#1462 userIdTargeting related mention in userId module doc
  dev-docs/modules/userId.md
Labels: LGTM

#1456 Buzzoola Bid Adapter doc
  dev-docs/bidders/buzzoola.md
Labels: LGTM

#1457 add datablocks bidder adapter documentation
  dev-docs/datablocks.md
  download.md
  overview/analytics.md
Labels: LGTM

#1454 [mgid] update supported media types
  dev-docs/bidders/mgid.md
Labels: LGTM

#1480 fix adsparc adapter parameters in documentation
  dev-docs/bidders/adsparc.md
Labels: LGTM

#1483 Added adxpremium analytics adapter
  overview/analytics.md
Labels: LGTM

#1485 Update download.md
  download.md
Labels: LGTM

#1429 add docs for the `storage.refreshInSeconds` configuration parameter
  dev-docs/modules/userId.md
Labels: LGTM, not merged yet

#1500 Add doc for new Rads adapter
  dev-docs/bidders/rads.md
Labels: LGTM

#1455 lemma.md
  dev-docs/bidders/lemma.md
Labels: LGTM, not merged yet

#1458 Telaria: Added SupplyChain Object documentation
  dev-docs/bidders/telaria.md
Labels: LGTM

#1476 OpenX Adapter: Added support for unifiedId and identityLink in the userId module
  dev-docs/bidders/openx.md
Labels: LGTM

#1478 Update doc file for TrustX Bid Adapter
  dev-docs/bidders/trustx.md
Labels: LGTM, not merged yet

#1486 Add Video Request Type functionality to documentation
  dev-docs/datablocks.md
Labels: LGTM
