Repository prebid/prebid.github.io, pull requests merged in 2019-08, with the labels that each got.

#1427 Add Loopme video adapter support
  dev-docs/bidders/loopme.md
Labels: LGTM

#1399 Add Meazy adapter docs
  dev-docs/bidders/meazy.md
Labels: LGTM, not merged yet

#1378 Add Sublime bid adapter
  dev-docs/bidders/sublime.md
Labels: LGTM, not merged yet

#1377 Integrate id link system
  dev-docs/modules/index.md
  dev-docs/modules/userId.md
Labels: LGTM

#1443 add indication for gdpr support to undertone adapter
  dev-docs/bidders/undertone.md
Labels: LGTM

#1424 Pb server docs
  _data/sidebar.yml
  prebid-server/endpoints/getuids.md
Labels: LGTM

#1450 Gamoshi: Add 9MediaOnline bidder adapter alias docs
  dev-docs/bidders/9MediaOnline.md
Labels: Pending PBJS Release
