Repository prebid/prebid.github.io, pull requests merged in 2020-04, with the labels that each got.

#1888 Media.net : adds Analytics Adapter
  download.md
  overview/analytics.md
Labels: LGTM, not merged yet

#1875 OpenX Adapter: Update user id modules
  dev-docs/bidders/openx.md
Labels: LGTM, not merged yet

#1885 Smartadserver adapter supports TCF V2 and USP/CCPA.
  dev-docs/bidders/smartadserver.md
Labels: LGTM, not merged yet

#1863 Onetag: video support
  dev-docs/bidders/onetag.md
Labels: LGTM, Pending PBJS Release

#1810 feature/alias-sync-config-option
  dev-docs/publisher-api-reference.md
Labels: LGTM, Pending PBJS Release

#1897 Fix bidder docs support for userid module
  dev-docs/bidders/9MediaOnline.md
  dev-docs/bidders/aardvark.md
  dev-docs/bidders/adtarget.md
  dev-docs/bidders/adxcg.md
  dev-docs/bidders/beachfront.md
  dev-docs/bidders/cleanmedia.md
  dev-docs/bidders/conversant.md
  dev-docs/bidders/emoteev.md
  dev-docs/bidders/gambid.md
  dev-docs/bidders/gamoshi.md
  dev-docs/bidders/gumgum.md
  dev-docs/bidders/justpremium.md
  dev-docs/bidders/kargo.md
  dev-docs/bidders/livewrapped.md
  dev-docs/bidders/medianet.md
  dev-docs/bidders/mobsmart.md
  dev-docs/bidders/onetag.md
  dev-docs/bidders/openx.md
  dev-docs/bidders/ozone.md
  dev-docs/bidders/pubmatic.md
  dev-docs/bidders/pulsepoint.md
  dev-docs/bidders/richaudience.md
  dev-docs/bidders/rubicon.md
  dev-docs/bidders/sharethrough.md
  dev-docs/bidders/smartrtb.md
  dev-docs/bidders/sonobi.md
  dev-docs/bidders/sovrn.md
  dev-docs/bidders/spotx.md
  dev-docs/bidders/triplelift.md
  dev-docs/bidders/ucfunnel.md
  dev-docs/bidders/undertone.md
  dev-docs/bidders/visx.md
  dev-docs/bidders/yieldlab.md
  dev-docs/bidders/yieldmo.md
  dev-docs/modules/userId.md
Labels: LGTM, not merged yet

#1878 OpenX: added tcf2 support
  dev-docs/bidders/openx.md
Labels: LGTM

#1882 GumGum: adds support for tcf 2.0
  dev-docs/bidders/gumgum.md
Labels: LGTM

#1883 yieldlift adapter docs
  dev-docs/bidders/yieldlift.md
Labels: LGTM

#1865 Doc file for new TheMediaGridNM Bid Adapter
  dev-docs/bidders/gridNM.md
Labels: LGTM

#1898 Added doc file for Converge Bid Adapter
  dev-docs/bidders/converge.md
Labels: LGTM

#1662 Added documentation for Hybrid.ai Adapter
  dev-docs/bidders/hybrid.md
Labels: LGTM

#1877 Bidlab adapter docs
  dev-docs/bidders/bidlab.md
Labels: LGTM

#1846 add adot bidder adapter documentation
  dev-docs/bidders/adot.md
Labels: LGTM, not merged yet

#1876 added automatad openRTB adapter doc
  dev-docs/bidders/automatadBidAdapter.md
Labels: LGTM

#1788 Windtalker adapter docs
  dev-docs/bidders/windtalker.md
Labels: LGTM

#1845 Add Schain support. Fidelity Media bid adapter
  dev-docs/bidders/fidelity.md
Labels: LGTM

#1844 adagioBidAdapter: SChain, TCF2 support features
  dev-docs/bidders/adagio.md
Labels: LGTM

#1889 Update platformio.md
  dev-docs/bidders/platformio.md
Labels: LGTM

#1902 Smartadserver add schain_supported to bidder doc
  dev-docs/bidders/smartadserver.md
Labels: LGTM

#1910 Gamoshi: Update aliases
  dev-docs/bidders/adtarget.md
Labels: question

#1785 Add new bid adapter for ConnectAd (formerly ServerBid Alias)
  dev-docs/bidders/connectad.md
Labels: LGTM, not merged yet

#1894 WIPES adapter docs
  dev-docs/bidders/wipes.md
Labels: LGTM, not merged yet

#1890 Quantcast: Added flags for TCF v2 and COPPA support.
  dev-docs/bidders/quantcast.md
Labels: LGTM, not merged yet

#1931 adding PBS privacy FAQ entry
  faq/prebid-server-faq.md
Labels: needs work

#1916 Adagio: update scope params column
  dev-docs/bidders/adagio.md
Labels: question

#1922 Create luponmedia.md
  dev-docs/bidders/luponmedia.md
Labels: LGTM, not merged yet

#1930 No bid version 1.2.5
  dev-docs/bidders/nobidBidAdapter.md
Labels: LGTM, not merged yet

#1925 LunaMedia Adapter Docs
  dev-docs/bidders/lunamedia.md
Labels: LGTM, not merged yet

#1926 Update gumgum.md
  dev-docs/bidders/gumgum.md
Labels: question

#1949 Pubstack Analytics Documentation
  download.md
  overview/analytics.md
Labels: LGTM, not merged yet
