Repository prebid/prebid.github.io, pull requests merged in 2020-07, with the labels that each got.

#2105 Appnexus: Adding tradedesk support
  dev-docs/bidders/appnexus.md
Labels: LGTM, Pending PBJS Release

#2109 Vidazoo Adapter: new adapter param `subDomain`
  dev-docs/bidders/vidazoo.md
Labels: LGTM, Pending PBJS Release

#2064 Add TCF2 Support for Invibes
  dev-docs/bidders/invibes.md
Labels: LGTM

#2070 Add lotame panorama ID
  dev-docs/modules/userId.md
Labels: LGTM, not merged yet

#2074 Update mediasquare adapter params
  dev-docs/bidders/mediasquare.md
Labels: LGTM

#2077 Remove Valueimpression Bid Adapter docs
  dev-docs/bidders/valueimpression.md
Labels: LGTM, not merged yet

#2095 adform supported userId modules
  dev-docs/bidders/adform.md
  dev-docs/bidders/adformOpenRTB.md
Labels: LGTM, not merged yet

#2119 Update TCF v2.0 and Params video
  .sass-cache/5eb7d1ad8f5d191bdc09ff706ecde9f0bb94342b/main.scssc
  dev-docs/bidders/appnexus.md
  dev-docs/bidders/richaudience.md
Labels: question

#2065 Add AMX RTB adapter documentation
  dev-docs/bidders/amx-rtb.md
Labels: LGTM, not merged yet

#2113 add docs for welect-bidder-adapter
  dev-docs/bidders/welect.md
Labels: LGTM

#2092 add default ttl to s2sconfig
  dev-docs/publisher-api-reference.md
Labels: LGTM, not merged yet

#2078 update id5 userId docs with new `pd` field
  dev-docs/modules/userId.md
Labels: LGTM, not merged yet

#2099 TrueReach Bidder Document
  dev-docs/bidders/truereach.md
Labels: LGTM, not merged yet

#2123 Performax adapter
  dev-docs/bidders/performax.md
Labels: LGTM, not merged yet

#2061 gdprEnforcement: adding Purpose 2
  dev-docs/modules/gdprEnforcement.md
Labels: Pending PBJS Release

#2091 New bid adapter for Smaato
  dev-docs/bidders/smaato.md
Labels: LGTM, not merged yet

#2112 new boldwin bid adapter
  dev-docs/bidders/boldwin.md
Labels: LGTM, not merged yet

#2134 Onetag update
  dev-docs/bidders/onetag.md
Labels: LGTM, not merged yet

#2135 Document subdomain to domain change for 4.0
  dev-docs/modules/userId.md
Labels: LGTM, Pending PBJS Release

#2137 [synacormedia] Update Documentation for latest changes
  dev-docs/bidders/synacormedia.md
Labels: question

#2144 Updating seedingAlliance Adapter
  dev-docs/bidders/seedingAlliance.md
Labels: LGTM, not merged yet

#2148 OpenX: Adding OpenX to list of hosted Prebid Server providers
  prebid-server/hosted-servers.md
Labels: question

#2048 Add host field into limelight bidder adapter docs
  dev-docs/bidders/project-limelight.md
Labels: LGTM

#2140 waardexAdapter, removed placementId
  dev-docs/bidders/waardex.md
Labels: LGTM, not merged yet

#2159 Saambaa bidder adapter Docs
  dev-docs/bidders/saambaa.md
Labels: LGTM

#2158 4.0 changes to video params
  dev-docs/bidder-adaptor.md
Labels: LGTM, not merged yet
