Repository prebid/prebid.github.io, pull requests merged in 2020-03, with the labels that each got.

#1796 NextRoll Bid Adapter docs
  dev-docs/bidders/nextroll.md
Labels: LGTM, not merged yet

#1806 update criteo userid name for appnexus bidder
  dev-docs/bidders/appnexus.md
Labels: LGTM, not merged yet

#1814 PubMatic adapter to support PM Deals
  dev-docs/bidders/pubmatic.md
Labels: LGTM, Pending PBJS Release

#1841 added dev-docs for vdo.ai bidder adapter
  dev-docs/bidders/vdoai.md
Labels: question

#1838 add mediaforce bid adapter docs
  dev-docs/bidders/mediaforce.md
Labels: LGTM

#1837 Nobid version 1.2.3
  dev-docs/bidders/nobidBidAdapter.md
Labels: LGTM

#1835 Lifestreet adapter 3.0 docs update
  dev-docs/bidders/lifestreet.md
Labels: LGTM

#1859 Nobid version 1.2.4
  dev-docs/bidders/nobidBidAdapter.md
Labels: LGTM, not merged yet

#1827 add UNICORN bid adapter docs
  dev-docs/bidders/unicorn.md
Labels: LGTM

#1880 defaultGdprScope flag
  dev-docs/modules/consentManagement.md
Labels: LGTM

#1836 Adds Clicktripz bidder adapter to dev-doc notes
  dev-docs/bidders/clicktripz.md
Labels: LGTM

#1821 Adnuntius Bidder documentation added
  .sass-cache/a8ae1fbf8fe3cf0ae44282e4f927a25624204c54/main.scssc
  dev-docs/bidders/adnuntius.md
Labels: LGTM

#1839 New evolution tech bid adapter
  dev-docs/bidders/evolution_tech.md
Labels: LGTM

#1849 Adfinity: gdpr support - true
  dev-docs/bidders/adfinity.md
Labels: LGTM

#1860 Add Valueimpression Bid Adapter docs
  dev-docs/bidders/valueimpression.md
Labels: LGTM

#1871 VIS.X: update docs regarding schain & userId support
  dev-docs/bidders/visx.md
Labels: LGTM

#1872 Media.net : add support for userId module
  dev-docs/bidders/medianet.md
Labels: LGTM

#1873 PubMatic bid adapter to support NetId User Module
  dev-docs/bidders/pubmatic.md
Labels: LGTM

#1874 Index Exchange: Registering user syncs
  dev-docs/bidders/indexExchange.md
Labels: LGTM

#1783 Add a new param for LiveIntent Id module. Describe the LiveIntent identity resolution.
  dev-docs/modules/userId.md
Labels: LGTM
