Repository prebid/prebid.github.io, pull requests merged in 2020-08, with the labels that each got.

#2166 Pubperf analytics adapter added.
  download.md
  overview/analytics.md
Labels: LGTM, not merged yet

#2141 Add docs for apstream adapter
  dev-docs/bidders/apstream.md
Labels: LGTM, not merged yet

#2172 AdButler Bid Adapter: Add 'extra' bid parameter description and example
  dev-docs/bidders/adbutler.md
Labels: LGTM, not merged yet

#2162 Undertone video docs
  dev-docs/bidders/undertone.md
Labels: question

#2151 RtbSape adapter
  dev-docs/bidders/rtbsape.md
Labels: LGTM

#2204 Brightcom support GDPR
  dev-docs/bidders/brightcom.md
Labels: LGTM, Pending PBJS Release

#2165 Analytics Module name changed
  download.md
  overview/analytics.md
Labels: LGTM, Pending PBJS Release

#2163 update triplelift docs for instream video
  dev-docs/bidders/triplelift.md
Labels: LGTM, not merged yet

#2180 IronSource adapter md file
  dev-docs/bidders/ironsource.md
Labels: LGTM, not merged yet

#2219 Update consentManagement.md to add AC string
  dev-docs/bidder-adaptor.md
  dev-docs/modules/consentManagement.md
Labels: LGTM, Pending PBJS Release

#2220 Add Bright Mountain Media Bid Adapter documentation
  dev-docs/bidders/brightmountainmedia.md
Labels: LGTM, not merged yet

#2234 mediago prebid bidder adapter docs
  dev-docs/bidders/mediago.md
Labels: LGTM, not merged yet

#2260 ID+ submodule
  dev-docs/modules/userId.md
Labels: question

#2033 New Adapter: Concert
  dev-docs/bidders/concert.md
Labels: LGTM, not merged yet

#2157 Add sspBC adapter
  dev-docs/bidders/sspBCAdapter.md
Labels: LGTM, not merged yet

#2275 Restored zoneId parameter in criteo bid adapter doc
  dev-docs/bidders/criteo.md
Labels: LGTM, not merged yet
