Repository prebid/prebid.github.io, pull requests merged in 2020-05, with the labels that each got.

#1954 DeepIntent: Gdpr support
  dev-docs/bidders/deepintent.md
Labels: LGTM, not merged yet

#1958 Show Inskin bid adapter as supporting GDPR
  dev-docs/bidders/inskin.md
Labels: LGTM

#1921 New bid adapter: Blue Billywig docs
  dev-docs/bidders/bluebillywig.md
Labels: LGTM

#1945 Konduit Accelerate documentation
  dev-docs/modules/index.md
  dev-docs/modules/konduit.md
  overview/analytics.md
Labels: LGTM, Pending PBJS Release

#1950 Admixer Bidder Adapter add gdpr and usp
  dev-docs/bidders/admixer.md
Labels: LGTM, Pending PBJS Release

#1951 Add Quantumdex Bid Adapter docs
  dev-docs/bidders/quantumdex.md
Labels: LGTM, Pending PBJS Release

#1952 New Adprime Prebid adapter
  dev-docs/bidders/adprime.md
Labels: LGTM, Pending PBJS Release

#1959 Add selectmedia to bidders list & downloads page
  dev-docs/bidders/selectmedia.md
Labels: LGTM

#1899 Update rakuten bidder
  dev-docs/bidders/rakuten.md
Labels: LGTM, not merged yet

#1976 New Trendqube bidder adapter
  dev-docs/bidders/trendqube.md
Labels: LGTM, not merged yet

#1955 update UNICORN BidAdapter docs
  dev-docs/bidders/unicorn.md
Labels: LGTM, not merged yet

#1963 New bidder adapter: pubgenius
  dev-docs/bidders/pubgenius.md
Labels: LGTM

#2012 change iabSubCatId name to primaryCatId
  dev-docs/bidder-adaptor.md
Labels: LGTM, not merged yet

#2004 Add min_duration and max_duration parameters to spotx.md
  dev-docs/bidders/spotx.md
Labels: LGTM, Pending PBJS Release

#2002 [rtbhouse.md] Add schain support
  dev-docs/bidders/rtbhouse.md
Labels: LGTM

#1989 Add craftBidAdapter
  dev-docs/bidders/craft.md
Labels: LGTM

#1988 add adWMG Analytics to the list
  download.md
  overview/analytics.md
Labels: LGTM

#1987 New adapter - videofy
  dev-docs/bidders/videofy.md
Labels: LGTM

#1978 AdPrime: Add context keywords parameter
  dev-docs/bidders/adprime.md
Labels: LGTM

#1977 Update Dailyhunt Doc
  dev-docs/bidders/dailyhunt.md
Labels: LGTM

#1965 Updated cpmstarBidAdapter docs
  dev-docs/bidders/cpmstar.md
Labels: LGTM, Pending PBJS Release

#1962 Create edgequeryx.md
  dev-docs/bidders/edgequeryx.md
Labels: LGTM
