Repository prebid/prebid.github.io, pull requests merged in 2020-06, with the labels that each got.

#2006 Adtarget documentation
  dev-docs/bidders/adtarget.md
Labels: LGTM, not merged yet

#1940 Submit Onomagic Adapter doc
  dev-docs/bidders/onomagic.md
Labels: LGTM, Pending PBJS Release

#2005 New Adaptor: Glimpse Protocol
  dev-docs/bidders/glimpseProtocol.md
Labels: LGTM, not merged yet

#2017 Mediasquare bidder documentation
  dev-docs/bidders/mediasquare.md
Labels: LGTM, not merged yet

#2026 Add module H12 Media
  dev-docs/bidders/h12media.md
Labels: LGTM, not merged yet

#1990 adds avocet bid adapter
  dev-docs/bidders/avocet.md
Labels: LGTM, not merged yet

#1986 add publisherId to appnexus adapter bid params
  dev-docs/bidders/appnexus.md
Labels: LGTM

#1961 Add documentation for AdPartner bid adapter
  dev-docs/bidders/adpartner.md
Labels: LGTM

#1973 Parrable ID System: Remove cookie storage configuration option
  dev-docs/modules/userId.md
Labels: LGTM

#1968 adform adapters support us_privacy and tcf2
  dev-docs/bidders/adform.md
  dev-docs/bidders/adformOpenRTB.md
Labels: LGTM

#1985 Konduit Accelerate documentation update
  dev-docs/modules/konduit.md
Labels: LGTM

#1997 Update dspx.md
  dev-docs/bidders/dspx.md
Labels: LGTM

#2007 GumGum: updates doc
  dev-docs/bidders/gumgum.md
Labels: LGTM

#2035 Add selectmedia video alias
  dev-docs/bidders/selectmediavideo.md
Labels: LGTM

#2037 Adagio: update scope params
  dev-docs/bidders/adagio.md
Labels: LGTM

#2040 Update doc file for TheMediaGrid Bid Adapter
  dev-docs/bidders/grid.md
Labels: LGTM

#2047 Update smartadserver.md
  dev-docs/bidders/smartadserver.md
Labels: LGTM

#2053 Add placement_type and position documentation to spotx adapter.
  dev-docs/bidders/spotx.md
Labels: LGTM

#2054 33Across: CCPA + Schain support
  dev-docs/bidders/33across.md
Labels: LGTM

#2063 Add Documentation for GMOSSP Adapter
  dev-docs/bidders/gmossp.md
Labels: LGTM

#2068 Vidazoo Adapter: Feature/user-id
  dev-docs/bidders/vidazoo.md
Labels: LGTM

#2069 added sharedId module to download page
  download.md
Labels: LGTM

#2073 update appnexus video params
  dev-docs/bidders/appnexus.md
Labels: LGTM

#2079 Update LiveIntent ID docs
  dev-docs/modules/userId.md
Labels: LGTM

#2076 updated supported id modules
  dev-docs/bidders/sovrn.md
Labels: LGTM

#2087 Floors multiple models
  dev-docs/modules/floors.md
Labels: LGTM

#2062 Adding userId to smartadserver.md
  dev-docs/bidders/smartadserver.md
Labels: LGTM
