Repository prebid/prebid.github.io, pull requests merged in 2020-09, with the labels that each got.

#2184 parrableIdSystem: Add an optional timezone and timezone offset allow/block filter
  dev-docs/modules/userId.md
Labels: LGTM, not merged yet

#2164 Add native support in ablida docs
  dev-docs/bidders/ablida.md
Labels: LGTM, not merged yet

#2198 Blue Billywig bid adapter - add video param to docs
  dev-docs/bidders/bluebillywig.md
Labels: LGTM, not merged yet

#2255 Document auctionDebug
  dev-docs/integrate-with-the-prebid-analytics-api.md
  dev-docs/publisher-api-reference.md
Labels: LGTM, not merged yet

#2334 Add gdpr supported in ablida docs
  dev-docs/bidders/ablida.md
Labels: LGTM, not merged yet

#2322 doc: add getEvents method to the public API
  dev-docs/publisher-api-reference.md
Labels: LGTM, not merged yet

#2320 Audigent HaloId Documentation
  dev-docs/modules/userId.md
Labels: LGTM, not merged yet

#2303 Backup only renderers
  dev-docs/show-outstream-video-ads.md
Labels: LGTM, not merged yet

#2301 New adapter "Cointraffic" added
  dev-docs/bidders/cointraffic.md
Labels: LGTM, not merged yet

#2298 Add additional parameters to config
  dev-docs/bidders/apstream.md
Labels: LGTM, not merged yet

#2294 MediaNet SChain Support
  dev-docs/bidders/medianet.md
Labels: LGTM, not merged yet

#2287 add Pub-X dev-docs
  dev-docs/bidders/pubx.md
Labels: LGTM, not merged yet

#2277 Added docs for Instream Video Ads Tracking
  _data/sidebar.yml
  dev-docs/integrate-with-the-prebid-analytics-api.md
  dev-docs/modules/index.md
  dev-docs/modules/instreamTracking.md
  dev-docs/publisher-api-reference.md
Labels: LGTM

#2340 Prebid SDK 1.8: bid response callback and OMSDK
  prebid-mobile/pbm-api/android/pbm-adunit-android.md
  prebid-mobile/pbm-api/android/pbm-targeting-params-android.md
  prebid-mobile/pbm-api/ios/pbm-adunit-ios.md
  prebid-mobile/pbm-api/ios/pbm-targeting-ios.md
Labels: needs work

#2221 Indicate new features in AMX RTB 1.1 Update
  dev-docs/bidders/amx-rtb.md
Labels: LGTM

#2332 GumGum: adds new params to gumgum doc
  dev-docs/bidders/gumgum.md
Labels: LGTM, Pending PBJS Release

#2233 welect: update docu to tcf2.0
  dev-docs/bidders/welect.md
Labels: LGTM

#2253 No bid version 1.2.7
  dev-docs/bidders/nobidBidAdapter.md
Labels: LGTM, Pending PBJS Release

#2305 ConnectAd docs update
  dev-docs/bidders/connectad.md
Labels: LGTM, not merged yet

#2361 Update invibes.md
  dev-docs/bidders/invibes.md
Labels: LGTM, not merged yet

#2338 Added md for new adaptor jixie
  dev-docs/bidders/jixie.md
Labels: LGTM, not merged yet

#2314 Add adnow bidder adaptor doc
  dev-docs/bidders/adnow.md
Labels: LGTM, not merged yet

#2329 Add adrelevantis bid adapter doc
  dev-docs/bidders/adrelevantis.md
Labels: LGTM, not merged yet

#2335 Logicad bidder support for native dev-docs
  dev-docs/bidders/logicad.md
Labels: LGTM, not merged yet

#2337 Adagio: add support for CCPA/COPPA
  dev-docs/bidders/adagio.md
Labels: LGTM, not merged yet

#2347 Smaato bid adapter: Optional bidder params to support in-app webview use cases
  dev-docs/bidders/smaato.md
Labels: LGTM, not merged yet

#2351 Intentiq id add params
  dev-docs/modules/userId.md
Labels: LGTM, not merged yet

#2353 Update Sublime adapter doc for v0.6
  dev-docs/bidders/sublime.md
Labels: LGTM, not merged yet

#2359 Update bridgewell.md
  dev-docs/bidders/bridgewell.md
Labels: LGTM, Pending PBJS Release

#2362 Add video support in ablida docs
  dev-docs/bidders/ablida.md
Labels: LGTM, not merged yet

#2364 SpotX adapter: add page param
  dev-docs/bidders/spotx.md
Labels: LGTM, not merged yet
