Repository prebid/prebid.github.io, pull requests merged in 2020-11, with the labels that each got.

#2452 Nobid: Support tcf2 and pbs
  dev-docs/bidders/nobidBidAdapter.md
Labels: LGTM, not merged yet

#2422 Adoppler: Add client parameter documentation.
  dev-docs/bidders/adoppler.md
Labels: LGTM, not merged yet

#2437 AMX RTB: indicate prebid server adapter and GVL ID
  dev-docs/bidders/amx-rtb.md
Labels: LGTM, not merged yet

#2432 Add support for Publisher Common ID Module in Sharethrough bid adapter docs
  dev-docs/bidders/sharethrough.md
Labels: LGTM, not merged yet

#2343 include a renderer for a specific mediaType
  dev-docs/show-outstream-video-ads.md
Labels: LGTM, Pending PBJS Release

#2370 feature/auction-options
  dev-docs/publisher-api-reference.md
  troubleshooting/troubleshooting-guide.md
Labels: LGTM

#2403 adding krushmedia pbjs adapter
  dev-docs/bidders/krushmedia.md
Labels: LGTM

#2412 Add skip params to Beachfront doc
  dev-docs/bidders/beachfront.md
Labels: LGTM

#2441 33Across: Updated for bidder support of video
  dev-docs/bidders/33across.md
Labels: LGTM

#2455 Adding detect missing sizes feature toggle
  dev-docs/bidders/indexExchange.md
Labels: LGTM

#2462 Smaato BidAdapter: Add support for userIds
  dev-docs/bidders/smaato.md
Labels: LGTM

#2396 MediaSquare: updated media_types + add glv_id
  dev-docs/bidders/mediasquare.md
Labels: LGTM, Pending PBJS Release

#2488 adform server bidder supports video
  dev-docs/bidders/adform.md
  dev-docs/bidders/adformPbs.md
Labels: LGTM, not merged yet

#2434 between adapter doc update: schain support
  dev-docs/bidders/between.md
Labels: LGTM, not merged yet

#2450 Gamoshi - Add new bid adaptor alias
  dev-docs/bidders/MobfoxX.md
Labels: LGTM

#2454 New lunamedia bid adapter
  dev-docs/bidders/lunamediahb.md
Labels: LGTM

#2458 Documentation for SilverMob adapter
  dev-docs/bidders/silvermob.md
Labels: LGTM

#2476 Update documentation for Qwarry bid adapter
  dev-docs/bidders/qwarry.md
Labels: LGTM

#2485 [AD-1023] JW Player - Set targeting info to bid.rtd
  dev-docs/modules/jwplayerRtdProvider.md
Labels: LGTM

#2503 Change placementId to be mandatory in undertone bidder docs
  dev-docs/bidders/undertone.md
Labels: question

#2510 add usp consent support
  dev-docs/bidders/adman.md
Labels: LGTM, not merged yet

#2369 Add Audigent RTD provider Docs
  dev-docs/modules/haloRtdProvider.md
Labels: LGTM

#2498 Feature: getNoBidsForAdUnitCode
  dev-docs/publisher-api-reference.md
Labels: LGTM
