Repository prebid/prebid.github.io, pull requests merged in 2021-01, with the labels that each got.

#2501 New mobfox bid adapter
  dev-docs/bidders/mobfoxpb.md
Labels: LGTM, not merged yet

#2588 Remove inmarId from Inmar bidder adapter params, add user IDs
  dev-docs/bidders/inmar.md
Labels: LGTM

#2590 created adbite.md
  dev-docs/bidders/adbite.md
Labels: LGTM

#2534 Documentation for Prebid VOX Bidder Adapter
  dev-docs/bidders/vox.md
Labels: LGTM

#2557 33Across: Remove Prebid Server Note
  dev-docs/bidders/33across.md
Labels: LGTM, not merged yet

#2562 GumGum: adds examples of set up and more descriptive scopes
  dev-docs/bidders/gumgum.md
Labels: LGTM, Pending PBJS Release

#2564 Engagey md file for engagey bid adapter
  dev-docs/bidders/engageya.md
Labels: LGTM

#2570 Sspbc adapter
  dev-docs/bidders/sspBCBidAdapter.md
Labels: LGTM

#2572 Add adblender bidder
  dev-docs/bidders/adblender.md
Labels: LGTM

#2573 Eplanning: documentation is modified
  dev-docs/bidders/eplanning.md
Labels: LGTM

#2575 Yieldlab: Update size handling
  dev-docs/bidders/yieldlab.md
Labels: LGTM

#2581 Readpeak: Add tagId to documentation
  dev-docs/bidders/readpeak.md
Labels: LGTM

#2582 Update Zeta docs to align with adapter updates
  dev-docs/bidders/zetaGlobal.md
Labels: LGTM

#2609 update adot adapter to add prebid server specifity
  dev-docs/bidders/adot.md
Labels: LGTM

#2614 Updating Revcontent documentation to include prebid-server
  dev-docs/bidders/revcontent.md
Labels: LGTM, not merged yet

#2616 ucfunnel adapter support schain, coppa, tcf2
  dev-docs/bidders/ucfunnel.md
Labels: LGTM

#2611 te medya new adaptor
  dev-docs/bidders/temedya.md
Labels: LGTM

#2584 changed vdo.ai bidder code to vdoai
  dev-docs/bidders/vdoai.md
Labels: LGTM

#2571 appnexus - add netid
  dev-docs/bidders/appnexus.md
Labels: LGTM

#2568 Create houseofpubs.md bidder instructions
  dev-docs/bidders/houseofpubs.md
Labels: LGTM

#2605 create rise.md
  dev-docs/bidders/rise.md
Labels: LGTM

#2612 Synacor Media: updated placementId property to tagId
  dev-docs/bidders/synacormedia.md
Labels: LGTM, not merged yet

#2580 GumGum: adds irisid as an optional param
  dev-docs/bidders/gumgum.md
Labels: LGTM, not merged yet

#2597 MediaFuse has pbs now
  dev-docs/bidders/mediafuse.md
Labels: LGTM, not merged yet

#2599 GothamAdsAdapter docs
  dev-docs/bidders/gothamads.md
Labels: LGTM, not merged yet

#2603 New AdTrue bidder
  dev-docs/bidders/adtrue.md
Labels: LGTM, not merged yet

#2610 add adomain to targeting keys table
  dev-docs/publisher-api-reference.md
Labels: LGTM, not merged yet

#2618 Add aliases info to "build adapter" section
  dev-docs/bidder-adaptor.md
Labels: LGTM, not merged yet

#2596 Rename Zemanta to Outbrain
  dev-docs/bidders/outbrain.md
Labels: LGTM

#2512 Feature: Multiple Prebid Servers
  dev-docs/bidders/prebidServer.md
Labels: LGTM

#2494 IX: Ad unit level properties support
  dev-docs/bidders/indexExchange.md
Labels: LGTM

#2637 Sonobi - Update Bidder Meta Data Dev Docs
  dev-docs/bidders/sonobi.md
Labels: LGTM

#2644 triplelift: updates dev-docs info
  dev-docs/bidders/triplelift.md
Labels: LGTM, not merged yet
