Repository prebid/prebid.github.io, pull requests merged in 2021-11, with the labels that each got.

#3322 Yieldmo Synthetic Inventory Module
  dev-docs/modules/yieldmoSyntheticInventoryModule.md
Labels: LGTM

#3395 Adding reference to prebid.js adapter .md file
  dev-docs/bidders/yahoossp.md
Labels: LGTM

#3251 Add Document For New Adapter: AdView
  dev-docs/bidders/adview.md
Labels: LGTM

#3304 Saamba Bid Adapter: update Prebid 5 compliance
  dev-docs/bidders/saambaa.md
Labels: LGTM

#3335 YieldOne Bid Adapter: Update doc.
  dev-docs/bidders/yieldone.md
Labels: LGTM, not merged yet

#3298 Add the documentation for mediakeys adapter
  dev-docs/bidders/mediakeys.md
Labels: LGTM

#3363 Yieldlab Adapter: update media_types docs
  dev-docs/bidders/yieldlab.md
Labels: LGTM

#3382 TheMediaGrid: update doc
  dev-docs/bidders/adlivetech.md
Labels: LGTM

#3386 OpenX update supported userIds
  dev-docs/bidders/openx.md
Labels: LGTM

#3385 Updated criteo bidder doc for video playbackmethod
  dev-docs/bidders/criteo.md
Labels: LGTM

#3406 Admixer: bid adapter and id system docs update
  dev-docs/bidders/admixer.md
  dev-docs/modules/userId.md
Labels: LGTM

#3397 Glimpse Adapter: Update overview and detail setup process
  dev-docs/bidders/glimpse.md
Labels: LGTM

#3413 Create generic bidder documentation
  prebid-server/developers/add-new-bidder-java.md
Labels: LGTM

#3420 iProm Bid Adapter: update versions included
  dev-docs/bidders/iprom.md
Labels: Pending PBJS Release

#3418 Add first-party data support to Beachfront doc
  dev-docs/bidders/beachfront.md
Labels: LGTM, not merged yet

#3414 new bidderSettings field - allowZeroCpmBids
  dev-docs/publisher-api-reference/bidderSettings.md
Labels: LGTM, Pending PBJS Release

#3409 AdmixerBidAdapter: add native support
  dev-docs/bidders/admixer.md
Labels: LGTM, not merged yet

#3408 Missena Bid Adapter: update with prebid compliance
  dev-docs/bidders/missena.md
Labels: LGTM, Pending PBJS Release

#3407 Add Intersection RTD Provider docs
  dev-docs/modules/intersectionRtdProvider.md
Labels: enhancement, LGTM, not merged yet

#3405 Limelight Digital Bid Adapter: Add optional Publisher ID field
  dev-docs/bidders/limelightDigital.md
Labels: LGTM, not merged yet

#3403 smartx Bid Adapter: refactor descriptions and adding "visibilityThreshold"
  dev-docs/bidders/smartx.md
Labels: LGTM, Pending PBJS Release

#3402 VIS.X: update docs
  dev-docs/bidders/visx.md
Labels: enhancement, LGTM

#3389 Adplus bid adapter doc added
  dev-docs/bidders/adplus.md
Labels: LGTM, not merged yet

#3384 Created gb_xandr.md docs
  dev-docs/bidders/goldbach.md
Labels: LGTM, not merged yet

#3347 Lupon Media Bid Adapter: update prebid 5 complianc
  dev-docs/bidders/luponmedia.md
Labels: LGTM, Pending PBJS Release

#2788 Document setting ppid from the userid module
  dev-docs/modules/userId.md
Labels: LGTM, not merged yet
