Repository prebid/prebid.github.io, pull requests merged in 2021-07, with the labels that each got.

#3064 initial commit vlyby markdown
  dev-docs/bidders/vlyby.md
Labels: LGTM

#3023 Added doc for Media.net RTD Module
  dev-docs/modules/medianetRtdProvider.md
Labels: LGTM, Pending PBJS Release

#3034 PixFuture bid adapter
  dev-docs/bidders/pixfuture.md
Labels: LGTM, Pending PBJS Release

#3046 Adserver.Online adapter docs
  dev-docs/bidders/aso.md
Labels: LGTM, Pending PBJS Release

#3063 Converge: update documentation
  dev-docs/bidders/converge.md
  dev-docs/bidders/converge_digital.md
Labels: LGTM, Pending PBJS Release

#3073 YieldOne Bid Adapter: add LiveRampID support.
  dev-docs/bidders/yieldone.md
Labels: LGTM, Pending PBJS Release

#3074 vdoai Bid Adapter - Support for Prebid 5.x
  dev-docs/bidders/vdoai.md
Labels: LGTM, Pending PBJS Release

#3076 Update docs for Adding Impactify back into Prebid 5.0
  dev-docs/bidders/impactify.md
Labels: LGTM, Pending PBJS Release

#3077 Updating Docs for Adding Adapter Back to Prebid 5.0
  dev-docs/bidders/vrtcal.md
Labels: LGTM, Pending PBJS Release

#3078 Gnet Bid Adapter: update to Prebid 5.x and remove externalId parameter
  dev-docs/bidders/gnet.md
Labels: LGTM, Pending PBJS Release

#3079 Update Docs for Adding Adapter back to Prebid 5.0
  dev-docs/bidders/pubx.md
Labels: LGTM, Pending PBJS Release

#3045 Add adRenderSucceeded to event list
  dev-docs/publisher-api-reference/getEvents.md
Labels: LGTM, not merged yet

#3054 Unruly r1 consolidated adapter
  dev-docs/bidders/unruly.md
Labels: LGTM, not merged yet

#3058 akamaiDAPIdSystem doc Update
  dev-docs/modules/userId.md
Labels: needs work, not merged yet

#3070 Logicad Bid Adapter: Support for Prebid 5.x
  dev-docs/bidders/logicad.md
Labels: LGTM, not merged yet

#3043 Kubient adapter. Add video support
  dev-docs/bidders/kubient.md
Labels: LGTM, not merged yet

#3056 RtbSape Bid Adapter: restore for Prebid 5.x
  dev-docs/bidders/rtbsape.md
Labels: LGTM, not merged yet

#3062 Smaato: update documentation
  dev-docs/bidders/smaato.md
Labels: LGTM, not merged yet

#3083 update s2sconfig for endpoint object config and add openx defaultVendor
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM, not merged yet

#3060 BrightMountainMedia: Add id5Id, sharedId support
  dev-docs/bidders/bmtm.md
Labels: LGTM

#3097 Updating OptimeraRTD with Optimera Bidder Adapter migration notes.
  dev-docs/modules/optimeraRtdProvider.md
Labels: LGTM

#3067 QuantcastId : Update userID module documentation with the latest description and parameters
  dev-docs/modules/userId.md
Labels: LGTM, not merged yet

#3135 Clickforce Bid Adapter: update prebid 5 compliance
  dev-docs/bidders/clickforce.md
Labels: LGTM, Pending PBJS Release

#3134 Adhese Bid Adapter:update with prebid 5 compliance
  dev-docs/bidders/adhese.md
Labels: LGTM, Pending PBJS Release

#3133 Aja Bid Adapter: update with prebid 5 compliance
  dev-docs/bidders/aja.md
Labels: LGTM, Pending PBJS Release

#3132 GetIntent bid adapter: update documentation
  dev-docs/bidders/getintent.md
Labels: LGTM, Pending PBJS Release

#3113 Document meta.demandSource
  dev-docs/bidder-adaptor.md
Labels: LGTM, Pending PBJS Release

#3105 Mantis Bid Adapter: update Prebid 5 compliance
  dev-docs/bidders/mantis.md
Labels: LGTM

#3103 Admixer Bid Adapter add kvTargeting option
  dev-docs/bidders/adblender.md
  dev-docs/bidders/admixer.md
  dev-docs/bidders/go2net.md
Labels: LGTM

#3102 No bid support for duration alias
  dev-docs/bidders/duration.md
Labels: LGTM, Pending PBJS Release

#3092 Add OperaAds Bid Adapter docs (#2)
  dev-docs/bidders/operaads.md
Labels: LGTM

#3085 Axonix adapter, added prebid server data and vendor id
  dev-docs/bidders/axonix.md
Labels: LGTM, not merged yet

#3069 updated iqm md file
  dev-docs/bidders/iqm.md
Labels: LGTM
