Repository prebid/prebid.github.io, pull requests merged in 2021-08, with the labels that each got.

#3152 Create uid2.0.md
  assets/images/UID2.png
  identity/UID2.0_testpage.md
  identity/prebid-identity.md
  identity/uid2.0.md
Labels: LGTM, not merged yet

#3154 Halo ID & RTD Documentation Update
  dev-docs/modules/haloRtdProvider.md
  dev-docs/modules/userId.md
Labels: needs work

#3151 MathildeAds adapter docs
  dev-docs/bidders/mathildeads.md
Labels: LGTM, not merged yet

#3144 TAPPX - Update tappx.md
  dev-docs/bidders/tappx.md
Labels: LGTM, not merged yet

#3109 InMobi: Update docs for native, schain
  dev-docs/bidders/inmobi.md
Labels: LGTM, not merged yet

#3106 added vidoomy bidder docs
  dev-docs/bidders/vidoomy.md
Labels: LGTM, not merged yet

#3075 Adagio Bid Adapter: add Prebid Server Adapter support
  dev-docs/bidders/adagio.md
Labels: LGTM, not merged yet

#3072 Update Teads bidder doc with support for some userIds
  dev-docs/bidders/teads.md
Labels: LGTM, not merged yet

#3000 Added docs for integr8
  dev-docs/bidders/integr8.md
Labels: LGTM, not merged yet

#3032 adtelligentIdSytem doc update
  dev-docs/modules/userId.md
Labels: LGTM, has conflicts, not merged yet

#3115 Smaato: Update documentation
  dev-docs/bidders/smaato.md
Labels: question

#3193 Cpmstar Bid Adapter: update prebid 5 compliance
  dev-docs/bidders/cpmstar.md
Labels: LGTM

#3190 InteractiveOffers - Parameters changed
  dev-docs/bidders/interactiveOffers.md
Labels: LGTM

#3189 Adkernel: documenting rtbanalytica alias
  dev-docs/bidders/rtbanalytica.md
Labels: LGTM

#3181 added brave bidder docs
  dev-docs/bidders/brave.md
Labels: LGTM, not merged yet

#3180 Mediakeys: add bidder adapter
  dev-docs/bidders/mediakeys.md
Labels: LGTM, not merged yet

#3179 Smartadserver Bid Adapter: Added support for Floors module
  dev-docs/bidders/smartadserver.md
Labels: LGTM, not merged yet

#3178 Krushmedia Bid Adapter: updates for Prebid 5.0
  dev-docs/bidders/krushmedia.md
Labels: LGTM, not merged yet

#3150 Logan adapter docs
  dev-docs/bidders/logan.md
Labels: LGTM

#3146 ContentExchange adapter docs
  dev-docs/bidders/contentexchange.md
Labels: LGTM

#3131 SmartHub docs
  dev-docs/bidders/smarthub.md
Labels: LGTM

#3159 add imuIdSystem doc
  dev-docs/modules/userId.md
Labels: LGTM, not merged yet

#3188 Add AdsYield adapter doc
  dev-docs/bidders/adsyield.md
Labels: question

#2971 IX Bid Adapter: FPD
  dev-docs/bidders/ix.md
Labels: LGTM, Pending PBJS Release

#3147 Added malltv analytics docs
  dev-docs/analytics/malltv.md
Labels: LGTM, Pending PBJS Release

#3123 Add example of bid filtering on meta object
  _data/sidebar.yml
  _layouts/example.html
  debugging/debugging.md
  dev-docs/common-issues.md
  dev-docs/examples/meta-bid-filtering
  dev-docs/examples/meta-bid-filtering.md
  dev-docs/faq.md
  dev-docs/prebid-troubleshooting-guide.md
  dev-docs/publisher-api-reference/getNoBids.md
  dev-docs/publisher-api-reference/setConfig.md
  dev-docs/troubleshooting-tips.md
  prebid/prebidjs.md
  troubleshooting/troubleshooting-guide.md
Labels: LGTM
