Repository prebid/prebid.github.io, pull requests merged in 2021-12, with the labels that each got.

#3417 Adf Support priceType in Prebid Server
  dev-docs/bidders/adf.md
Labels: LGTM, Pending PBS Release

#3426 Admixer Bid Adapter: add alias futureads
  dev-docs/bidders/futureads.md
Labels: LGTM, Pending PBJS Release

#3443 Livewrapped: Support for first party data
  dev-docs/bidders/livewrapped.md
Labels: Pending PBJS Release

#3450 FeedAd Bid Adapter: added documentation for decoration parameter
  dev-docs/bidders/feedad.md
Labels: LGTM

#3445 Add didnavideo doc
  dev-docs/bidders/didnavideo.md
Labels: LGTM

#3436 Ventes Bidder Md file updated
  dev-docs/bidders/ventes.md
Labels: LGTM

#3432 Prebid Adman Bidder Adapter: add lotamePanoramaId
  dev-docs/bidders/adman.md
Labels: LGTM

#3416 RTD: Add 'onBidRequest' event handler for RTD submodules
  dev-docs/add-rtd-submodule.md
Labels: LGTM

#3431 Update Apacdex, Quantumdex, Valueimpression docs
  dev-docs/bidders/apacdex.md
  dev-docs/bidders/quantumdex.md
  dev-docs/bidders/valueimpression.md
Labels: LGTM
