Repository prebid/prebid.github.io, pull requests merged in 2021-04, with the labels that each got.

#2776 Added support for userIds
  dev-docs/bidders/invibes.md
Labels: LGTM

#2780 update documention of doceree adapter
  dev-docs/bidders/doceree.md
Labels: LGTM, not merged yet

#2787 Improved documentation on Registering on Timeout
  dev-docs/bidder-adaptor.md
Labels: LGTM

#2789 AdDefend Bid Adapter: add md file for bidder
  dev-docs/bidders/addefend.md
Labels: LGTM, not merged yet

#2790 Update rads.md
  dev-docs/bidders/rads.md
Labels: LGTM

#2795 Update Sovrn doc to show floor module support
  dev-docs/bidders/sovrn.md
Labels: LGTM

#2799 OpenX docs update
  dev-docs/bidders/openx.md
Labels: LGTM

#2800 IX adapter has priceFloors module support
  dev-docs/bidders/ix.md
Labels: LGTM

#2808 Roundel Alias Documentation
  dev-docs/bidders/roundel.md
Labels: LGTM, Pending PBJS Release

#2813 Update Criteo adapter doc for PBS support
  dev-docs/bidders/criteo.md
Labels: LGTM, not merged yet

#2821 Add Impactify bidder documentation
  dev-docs/bidders/impactify.md
Labels: LGTM, not merged yet

#2823 Adkernel: actualizing documentation
  dev-docs/analytics/adkernelAdn.md
  dev-docs/bidders/adkernel.md
  dev-docs/bidders/adkernelAdn.md
Labels: LGTM, Pending PBJS Release

#2666 Add UserId Submodule AdmixerId
  dev-docs/modules/userId.md
  download.md
Labels: LGTM, not merged yet

#2762 dev-docs: describe Adloox Prebid Analytics Adapter
  dev-docs/analytics/adloox.md
Labels: LGTM, not merged yet

#2819 Bidmachine adapter docs
  dev-docs/bidders/bidmachine.md
Labels: LGTM, not merged yet

#2782 Docs for Zeta Global Ssp adapter
  dev-docs/bidders/zeta_global_ssp.md
Labels: LGTM, not merged yet

#2826 Adding supported userids modules to logicad bid adapter documentation
  dev-docs/bidders/logicad.md
Labels: LGTM, not merged yet

#2832 Updated Blue Billywig adapter documentation with new rendererSettings param
  dev-docs/bidders/bluebillywig.md
Labels: LGTM, not merged yet

#2838 Add gdpr and tcf2 supported parameters
  dev-docs/bidders/readpeak.md
Labels: LGTM, Pending PBJS Release

#2840 Between bidder: update dev-doc
  dev-docs/bidders/between.md
Labels: LGTM, Pending PBJS Release

#2841 33Across: Document support for User ID module
  dev-docs/bidders/33across.md
Labels: LGTM, Pending PBJS Release

#2846 Update doc file for TrustX
  dev-docs/bidders/trustx.md
Labels: LGTM, not merged yet

#2850 Yieldmo out-stream support documentation
  dev-docs/bidders/yieldmo.md
Labels: LGTM, not merged yet

#2872 Sharethrough: Add Support for COPPA
  dev-docs/bidders/sharethrough.md
Labels: LGTM

#2871 Shinez bid adapter documentation
  dev-docs/bidders/shinez.md
Labels: LGTM

#2863 Sspbc adapter - update parameter list
  dev-docs/bidders/sspBC.md
Labels: LGTM

#2852 Smile Wanted : Update doc to support User Sync
  dev-docs/bidders/smilewanted.md
Labels: LGTM

#2834 Nativo Bidder Adapter
  dev-docs/bidders/nativo.md
Labels: LGTM

#2830 deepintent docs added
  dev-docs/modules/userId.md
  download.md
Labels: LGTM, not merged yet

#2820 Docs for new adriver bidder
  dev-docs/bidders/adriver.md
Labels: LGTM

#2806 Documentation for Kobler bidder adapter
  dev-docs/bidders/kobler.md
Labels: LGTM, not merged yet

#2807 Mass custom configs
  dev-docs/modules/index.md
  dev-docs/modules/mass.md
Labels: has conflicts

#2828 Docs for gnet bidder
  dev-docs/bidders/gnet.md
Labels: LGTM, not merged yet

#2887 Adf prebid-server adapter added
  dev-docs/bidders/adf.md
Labels: LGTM, Pending PBJS Release

#2837 Zeta global ssp
  dev-docs/bidders/zeta_global_ssp.md
Labels: has conflicts, needs work
