Repository prebid/prebid.github.io, pull requests merged in 2022-12, with the labels that each got.

#4186 added filename support on download page
  dev-docs/bidders/acuityads.md
  dev-docs/bidders/kueezrtb.md
  download.md
Labels: LGTM

#4198 Adagio: update userIds providers support
  dev-docs/bidders/adagio.md
Labels: LGTM

#4179 Add smn adapter
  dev-docs/bidders/smn.md
Labels: LGTM, Pending PBJS Release

#4163 Yieldlab Bid Adapter update dev docs
  dev-docs/bidders/yieldlab.md
Labels: LGTM, Pending PBJS Release

#4162 Add new adapter Redtram
  dev-docs/bidders/redtram.md
Labels: LGTM, Pending PBJS Release

#4142 Seedtag - update doc example for inBanner and inStream examples
  dev-docs/bidders/seedtag.md
Labels: LGTM, not merged yet

#4029 Update to prebid website for the new GrowthCode Analysis Module
  dev-docs/analytics/growthcode.md
Labels: LGTM, not merged yet

#4206 replaced `%RESPONSE_ID_LIST` with `%ID_LIST%`.
  prebid-server/hosting/pbs-database.md
Labels: LGTM

#4219 update algorix support gdpr
  dev-docs/bidders/algorix.md
Labels: LGTM

#4215 pbjs: document default FPD enrichment
  dev-docs/bidder-adaptor.md
  dev-docs/modules/enrichmentFpdModule.md
Labels: LGTM, Pending PBJS Release

#4222 Added section related to Topics IFrame configuration
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM, Pending PBJS Release

#4211 Adnuntius Bid Adapter: docu change to support native
  dev-docs/bidders/adnuntius.md
Labels: LGTM, Pending PBJS Release

#4082 PBJS: document new `enableAnalytics` event filter parameters
  dev-docs/publisher-api-reference/enableAnalytics.md
  overview/analytics.md
Labels: LGTM, not merged yet

#4197 Added a description of the disabledSendingStatisticData option for th…
  dev-docs/bidders/nextMillennium.md
Labels: LGTM, not merged yet

#4201 Updates to document the new UID2 module functionality in the Prebid.js PR #9264
  dev-docs/modules/userid-submodules/unified2.md
Labels: LGTM, not merged yet

#4138 Video Module: Ad Queue
  prebid-video/video-module.md
Labels: LGTM, not merged yet

#4125 Add dev documentation for smartytech adapter
  dev-docs/bidders/smartytech.md
Labels: LGTM, Pending PBJS Release

#4188 New Adapter: Globalsun
  dev-docs/bidders/globalsun.md
Labels: LGTM, not merged yet

#4202 Confiant's RTD Provider documentation
  dev-docs/modules/confiantRtdProvider.md
Labels: LGTM, not merged yet
