Repository prebid/prebid.github.io, pull requests merged in 2022-07, with the labels that each got.

#3874 updating Taboola adapter documentation
  dev-docs/bidders/taboola.md
Labels: LGTM

#3887 Updated user sync content
  dev-docs/bidders/ix.md
Labels: LGTM

#3851 Updated VRTCAL support flags
  dev-docs/bidders/vrtcal.md
Labels: question, LGTM

#3862 PBJS: document the NATIVE feature flag for bid adapters
  dev-docs/bidder-adaptor.md
Labels: LGTM

#3838 Add ras bid adapter docs
  dev-docs/bidders/ras.md
Labels: LGTM, not merged yet

#3849 New Bid Adapter Dev Docs: newspassid
  dev-docs/bidders/newspassid.md
Labels: LGTM, Pending PBJS Release

#3900 update SelectMedia gvlid
  dev-docs/bidders/selectmedia.md
Labels: LGTM

#3873 1plusX RTD submodule docs
  dev-docs/modules/1plusXRtdProvider.md
Labels: LGTM, not merged yet

#3882 Seedtag - update bidder doc for usp/ccpa compliance
  dev-docs/bidders/seedtag.md
Labels: LGTM, not merged yet

#3886 Added descriptions of ID5 and Criteo to AdGenerationDoc.
  dev-docs/bidders/adgeneration.md
Labels: LGTM, not merged yet

#3908 add ortb-blocking metadata
  _layouts/bidder.html
  dev-docs/bidder-adaptor.md
  dev-docs/bidder-data.csv
  dev-docs/bidders/rubicon.md
  dev-docs/pbs-bidders.md
  prebid-server/developers/add-new-bidder-go.md
  prebid-server/developers/add-new-bidder-java.md
Labels: LGTM

#3911 add doc: imRtdModule
  dev-docs/modules/imRtdProvider.md
Labels: LGTM

#3850 Update bucksense.md added gdpr_supported: true
  dev-docs/bidders/bucksense.md
Labels: question

#3914 add ID5 support
  dev-docs/bidders/yieldone.md
Labels: LGTM, not merged yet

#3907 BLIINK Doc : Update doc by removing placement, adding optional imageUrl and setting pbs to true
  dev-docs/bidders/bliink.md
Labels: LGTM, Pending PBJS Release

#3906 add schain and coppa to Consumable docs
  dev-docs/bidders/consumable.md
Labels: LGTM, Pending PBJS Release

#3898 Prisma Bid Adapter: add new bid adapter
  dev-docs/bidders/prisma.md
Labels: LGTM

#3893 Add support for price floors and schain in onetag.md
  dev-docs/bidders/onetag.md
Labels: LGTM

#3883 Add native handling for PBS only
  .gitignore
  dev-docs/bidders/smartadserver.md
Labels: LGTM, Pending PBS Release

#3889 GDPR enforcement module: document new `strictStorageEnforcement` config
  dev-docs/modules/gdprEnforcement.md
Labels: LGTM, not merged yet

#3890 videonow bidder adapter docs update
  dev-docs/bidders/videonow.md
Labels: LGTM, not merged yet

#3910 StroeerCore Bid Adapter: add schain support
  dev-docs/bidders/stroeerCore.md
Labels: LGTM, not merged yet

#3913 Updated missing params for mobilefuse
  dev-docs/bidders/mobilefuse.md
Labels: LGTM

#3923 Update permutive rtd dev docs
  assets/images/dev-docs/modules/permutiveRtdProvider-integration-create.png
  assets/images/dev-docs/modules/permutiveRtdProvider-integration-update.png
  dev-docs/modules/permutiveRtdProvider.md
Labels: LGTM

#3929 User Id Module - EID directions
  dev-docs/modules/userId.md
Labels: LGTM

#3930 Gumgum Bid Adapter: Updated document to include s2s example for skins
  dev-docs/bidders/gumgum.md
Labels: LGTM

#3931 UNICORN: update bidder params
  dev-docs/bidders/unicorn.md
Labels: LGTM

#3922 Blue adapter creation
  dev-docs/bidders/blue.md
Labels: LGTM, not merged yet
