Repository prebid/prebid.github.io, pull requests merged in 2022-10, with the labels that each got.

#4028 Update to prebid website for the new GrowthCode UserID Module
  dev-docs/modules/userId.md
Labels: LGTM

#4017 TheMediaGrid: added native support for s2s adapter only
  dev-docs/bidders/grid.md
Labels: LGTM

#4030 Prebid Core: Document setting custom cpm rounding config
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM

#4011 Conversant analytics adapter - initial release documentation
  dev-docs/analytics/conversant.md
Labels: needs work, not merged yet

#4003 Vuukle Bid Adapter: support gdpr/usp/coppa/schain/gvlid
  dev-docs/bidders/vuukle.md
Labels: LGTM

#3948 OneKey RTD Module & OneKey Id Submodule: initial release
  dev-docs/modules/oneKeyRtdProvider.md
  dev-docs/modules/userId.md
Labels: LGTM

#4018 AndBeyond.Media adapter: update bidder code
  dev-docs/bidders/andBeyondMedia.md
Labels: LGTM, Pending PBJS Release

#4068 Disclosure in consumable.md
  dev-docs/bidders/consumable.md
Labels: LGTM

#4050 PBJS: document fpdEnrichment ua client hints support
  dev-docs/modules/enrichmentFpdModule.md
Labels: LGTM

#4026 OMNS: Update documentation for the new Teads User Id Module
  dev-docs/modules/userId.md
  download.md
Labels: LGTM

#4079 updating Ogury Bidder documentation
  dev-docs/bidders/ogury.md
Labels: LGTM, not merged yet

#4072 Added support for 3rd party user IDs
  dev-docs/bidders/vrtcal.md
Labels: LGTM

#4066 PBJS: Document new `bidRejected` event
  dev-docs/publisher-api-reference/getEvents.md
Labels: LGTM

#4086 PBJS: document `adUnit.bids[].renderer`
  dev-docs/adunit-reference.md
  dev-docs/show-outstream-video-ads.md
Labels: LGTM, Pending PBJS Release

#4084 Ias rtd module optional parameters
  dev-docs/modules/iasRtdProvider.md
Labels: LGTM, Pending PBJS Release

#4071 Bidstack adapter documentation
  dev-docs/bidders/bidstack.md
Labels: LGTM, not merged yet

#4067 MediaNet Adapter: Changed AAX client docs flag
  dev-docs/bidders/aax.md
Labels: LGTM, not merged yet

#4064 Smaato: Adding native ads to docs
  dev-docs/bidders/smaato.md
Labels: LGTM, not merged yet

#4056 Magnite Analytics Adapter
  dev-docs/analytics/magnite.md
Labels: LGTM, Pending PBJS Release

#4106 teads adapter: Create note to avoid 7.20.0 and 7.21.0 when downloading Prebid.js
  dev-docs/bidders/teads.md
  download.md
Labels: LGTM

#4109 Update to prebid openRTB fork
  prebid-server/developers/add-new-bidder-go.md
Labels: LGTM

#4115 Update mediago.md
  dev-docs/bidders/mediago.md
Labels: LGTM

#4070 Add Oxxion Rtd Provider
  dev-docs/modules/oxxionRtdProvide.md
Labels: LGTM

#4100 Video Module: Initial Release
  .ruby-version
  _data/sidebar.yml
  dev-docs/add-video-submodule.md
  dev-docs/adunit-reference.md
  dev-docs/modules/jwplayerVideoProvider.md
  dev-docs/modules/video.md
  dev-docs/modules/videojsVideoProvider.md
  dev-docs/publisher-api-reference/addAdUnits.md
  dev-docs/publisher-api-reference/setConfig.md
  prebid-video/video-getting-started.md
  prebid-video/video-integrating-solo.md
  prebid-video/video-module.md
Labels: Pending PBJS Release

#4085 Improve Digital adapter: adding publisherId param
  dev-docs/bidders/improvedigital.md
Labels: LGTM, not merged yet

#4065 Clickonometrics: add gvl_id, update param name
  dev-docs/bidders/ccx.md
Labels: LGTM, not merged yet

#4073 PBJS: document new return value from `requestBids`
  dev-docs/publisher-api-reference/requestBids.md
Labels: LGTM, not merged yet

#4080 ConnectID User ID module: Document extended configuration options
  dev-docs/modules/userId.md
Labels: LGTM

#4083 Added new adapter builder parameter for PBS-Go
  prebid-server/developers/add-new-bidder-go.md
Labels: LGTM

#4095 AAX Blockmeter RealTime Data Module Documentation
  dev-docs/modules/aaxBlockmeterRtdProvider.md
Labels: LGTM

#4097 PBJS: document new `ttlBuffer` settings
  dev-docs/adunit-reference.md
  dev-docs/publisher-api-reference/requestBids.md
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM
