Repository prebid/prebid.github.io, pull requests merged in 2022-11, with the labels that each got.

#4112 Honor pbjs setting on bidder page #fix 4111
  _layouts/bidder.html
Labels: bug

#4081 Mgid RTD module docs
  dev-docs/modules/mgidRtdProvider.md
Labels: LGTM, Pending PBJS Release

#4120 IX Bid Adapter: docs update for siteId overrides
  dev-docs/bidders/ix.md
Labels: LGTM, not merged yet

#4118 AdMatic Bidder PR Doc
  dev-docs/bidders/admatic.md
Labels: LGTM, Pending PBJS Release

#4127 Clickonometrics: update
  dev-docs/bidders/ccx.md
Labels: LGTM

#4134 VIS.X adapter update docs
  dev-docs/bidders/visx.md
Labels: LGTM

#4103 New Adapter: Appush
  dev-docs/bidders/appush.md
Labels: LGTM, not merged yet

#4135 Prebid Mobile changes for the version `2.0.4`
  prebid-mobile/modules/rendering/android-sdk-integration-admob.md
  prebid-mobile/modules/rendering/android-sdk-integration.md
  prebid-mobile/modules/rendering/ios-sdk-integration-admob.md
  prebid-mobile/pbm-api/android/code-integration-android.md
  prebid-mobile/pbm-api/ios/code-integration-ios.md
Labels: question, LGTM

#4141 Microad Bid Adapter: Support for User Ids
  dev-docs/bidders/microad.md
Labels: LGTM, Pending PBJS Release

#4131 Update Conversant branding to Epsilon
  _data/partners.yml
  assets/images/partners/tech/conversant_logo.png
  assets/images/partners/tech/epsilon_logo.png
  deprecated/old_index_md_content.html
  dev-docs/analytics/epsilon.md
  dev-docs/bidders/epsilon.md
  prebid-server/endpoints/openrtb2/pbs-endpoint-video.md
Labels: LGTM, Pending PBJS Release

#4087 pbs-go dev alias instructions
  prebid-server/developers/add-new-bidder-go.md
Labels: LGTM

#4116 AAX Adapter: Added medianet alias code
  dev-docs/bidders/aax.md
Labels: LGTM

#3987 add viqeo prebid adapter
  dev-docs/bidders/viqeo.md
Labels: LGTM

#4045 Update dacid userid module documents
  dev-docs/modules/userId.md
Labels: LGTM

#4052 docs(module): kueezrtb adapter dev-docs
  dev-docs/bidders/kueezrtb.md
Labels: LGTM

#4076 SUNT Content Bid Adapter: New Adapter
  dev-docs/bidders/suntContent.md
Labels: LGTM

#4094 freewheel ssp add prebid go adapter - update freewheel dev doc
  dev-docs/bidders/freewheelssp.md
Labels: LGTM

#4089 fledgeForGpt Module Docs
  dev-docs/modules/fledgeForGpt.md
Labels: LGTM

#4117 Add zeusPrimeRtdProvider Documentation Page
  dev-docs/modules/zeusPrimeRtdProvider.md
Labels: LGTM

#4144 Taboola Bid Adapter: Remove Dynamic Endpoint Param
  dev-docs/bidders/taboola.md
Labels: LGTM

#4154 smartx Bid Adapter: Add support for Schain
  dev-docs/bidders/smartx.md
Labels: LGTM

#4155 TheMediaGrid: doc update
  dev-docs/bidders/grid.md
Labels: LGTM

#4146 Add captifyRtdProvider Documentation Page
  dev-docs/modules/captifyRtdProvider.md
Labels: needs work
