Repository prebid/prebid.github.io, pull requests merged in 2022-02, with the labels that each got.

#3542 Snowflake ID is now Hyper ID and document new SharedID changes
  dev-docs/modules/userId.md
  download.md
Labels: LGTM, not merged yet

#3520 Tappx :: avoid host
  dev-docs/bidders/tappx.md
Labels: question

#3491 Document `s2sConfig.allowUnknownBidderCodes`
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM, not merged yet

#3485 update weborama RTD submodule doc for v 6.9.0
  dev-docs/modules/weboramaRtdProvider.md
Labels: LGTM, not merged yet

#3541 setConfig(bidCacheFilterFunction)
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM, Pending PBJS Release

#3454 Added readme for Vibrant Media bidder adapter
  dev-docs/bidders/vibrantmedia.md
Labels: LGTM, not merged yet

#3427 Add doc for brandmetricsRtdProvider
  dev-docs/modules/brandmetricsRtdProvider.md
Labels: LGTM, not merged yet

#3399 Initial document for groupm as pubmatic alias
  dev-docs/bidders/groupm.md
Labels: LGTM

#3381 Generic viewability module
  dev-docs/modules/viewability.md
Labels: LGTM, not merged yet

#3294 DeepIntent: video docs added
  dev-docs/bidders/deepintent.md
Labels: needs work

#3552 [StroeerCore] GDPR is now supported
  dev-docs/bidders/stroeerCore.md
Labels: LGTM

#3549 Mediakeys documentation improvements
  dev-docs/bidders/mediakeys.md
Labels: LGTM

#3526 Update OpenX bidder docs with FPD
  dev-docs/bidders/openx.md
Labels: LGTM, not merged yet

#3554 IQzone Bidder: add new param
  dev-docs/bidders/iqzone.md
Labels: LGTM, Pending PBJS Release

#3548 Mediasquare Bid Adapter: add floor module support
  dev-docs/bidders/mediasquare.md
Labels: LGTM, Pending PBJS Release

#3041 BidMyAdz adapter docs
  dev-docs/bidders/bidmyadz.md
Labels: question, LGTM, not merged yet

#3451 Adding pilotx documentation
  dev-docs/bidders/pilotx.md
Labels: needs work

#3476 Kubient COPPA support
  dev-docs/bidders/kubient.md
Labels: LGTM

#3480 displayio docs
  dev-docs/bidders/displayio.md
Labels: LGTM

#3530 [:art:] chore: Upgrade adot adapter documentation
  dev-docs/bidders/adot.md
Labels: LGTM

#3469 updated lkqd bidder
  dev-docs/bidders/lkqd.md
Labels: LGTM, not merged yet

#3536 Just ID docs
  dev-docs/modules/userId.md
  download.md
Labels: LGTM, not merged yet

#3556 Nexx360 bid Adapter added
  dev-docs/bidders/nexx360.md
Labels: LGTM, not merged yet

#3558 add bigRichmedia adapter
  dev-docs/bidders/big-richmedia.md
Labels: LGTM, not merged yet

#3559 PrebidServer DemandSource metadata field
  prebid-server/developers/add-new-bidder-java.md
Labels: LGTM, not merged yet

#3584 Added description to userID modules to section download and userId
  dev-docs/bidders/adquery.md
  dev-docs/modules/userId.md
  download.md
Labels: LGTM

#3588 Document seatbid.bid.ext.prebid.meta.demandsource
  prebid-server/developers/add-new-bidder-go.md
Labels: LGTM

#3577 Add TTD bidder dev documentation
  dev-docs/bidders/ttd.md
Labels: LGTM, not merged yet
