Repository prebid/prebid.github.io, pull requests merged in 2022-01, with the labels that each got.

#3449 Update Sharethrough documentation to include video media type, floors, and safeframes
  dev-docs/bidders/sharethrough.md
Labels: LGTM

#3430 Algorix: add Server Region Support
  dev-docs/bidders/algorix.md
Labels: LGTM, Pending PBS Release

#3482 Prebid Mobile: Add warning for GAM integration on iOS.
  prebid-mobile/modules/rendering/ios-sdk-Integration.md
  prebid-mobile/modules/rendering/ios-sdk-integration-gam.md
Labels: LGTM

#3466 Outbrain adapter: Add support for id5Id
  dev-docs/bidders/outbrain.md
Labels: LGTM, not merged yet

#3461 ozone 2.7.0 doc updates
  dev-docs/bidders/ozone.md
Labels: LGTM, not merged yet

#3429 Loglylift adapter
  dev-docs/bidders/loglylift.md
Labels: LGTM, Pending PBJS Release

#3424 Add 's2sConfig.syncTimeout' option
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM, not merged yet

#3415 update weborama RTD submodule doc to reflect latest feature update
  dev-docs/modules/weboramaRtdProvider.md
Labels: LGTM, not merged yet

#3373 VideoByte update docs
  dev-docs/bidders/videobyte.md
Labels: LGTM, Pending PBS Release

#3387 add bizzclick previd-server adapter
  dev-docs/bidders/bizzclick.md
Labels: LGTM, not merged yet

#3401 Add targetingControls.addTargetingKeys configuration option
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM, Pending PBJS Release

#3396 Update Coinzilla for Prebid-Server support
  dev-docs/bidders/coinzilla.md
Labels: LGTM, not merged yet

#3411 TargetVideo adapter update
  dev-docs/bidders/targetvideo.md
Labels: LGTM, not merged yet

#3404 33across: Add support for SRA
  dev-docs/bidders/33across.md
Labels: LGTM, not merged yet

#3422 Update userId.md
  dev-docs/modules/userId.md
Labels: LGTM

#3489 ETARGET adapter ortb2 site and user specs
  dev-docs/bidders/etarget.md
Labels: LGTM

#3446 IX Bid Adapter: Add ID5, Lotame Panorama ID, Epsilon Publisher Link, Audigent Halo ID, SharedID
  dev-docs/bidders/ix.md
Labels: LGTM, Pending PBJS Release

#3495 Adform: all userIds supported
  dev-docs/bidders/adf.md
  dev-docs/bidders/adform.md
Labels: LGTM

#3488 Automatad Adapter: update first party data status in adapter doc
  dev-docs/bidders/automatad.md
Labels: LGTM

#3464 Appnexus adapter: Placement_id update
  dev-docs/bidders/appnexus.md
Labels: LGTM

#3500 MediaNet adapter: Adding MediaNet into Prebid server bidder list
  dev-docs/bidders/medianet.md
Labels: LGTM

#3503 Gnet Bid Adapter: add new parameter
  dev-docs/bidders/gnet.md
Labels: LGTM, Pending PBJS Release, not merged yet

#3502 SiteId is no longer required for the conversant adapter
  dev-docs/bidders/conversant.md
Labels: LGTM

#3460 Zeta Global SSP Analytics Adapter: add docs for new analytics adapter
  dev-docs/analytics/zeta_global_ssp.md
Labels: needs work

#3453 Update userId.md
  dev-docs/modules/userId.md
Labels: LGTM

#3490 Videobyte - Update media types and note
  dev-docs/bidders/videobyte.md
Labels: question

#3511 Criteo - Add schain support
  dev-docs/bidders/criteo.md
Labels: LGTM

#3471 Evolution Bid Adapter: compliance with Prebid v5
  dev-docs/bidders/e_volution.md
Labels: LGTM

#3477 Update vidoomy with pbs support
  dev-docs/bidders/vidoomy.md
Labels: LGTM

#3528 Conversant adapter now supports FPD options through ortb2 and ortb2Imp
  dev-docs/bidders/conversant.md
Labels: Pending PBJS Release

#3523 Appnexus Bid Adapter: auction level keywords
  dev-docs/bidders/appnexus.md
Labels: Pending PBJS Release

#3509 Audigent Halo -> Hadron Rebranding
  dev-docs/bidders/beachfront.md
  dev-docs/bidders/ix.md
  dev-docs/bidders/openx.md
  dev-docs/bidders/pulsepoint.md
  dev-docs/modules/hadronRtdProvider.md
  dev-docs/modules/haloRtdProvider.md
  dev-docs/modules/userId.md
  download.md
Labels: LGTM

#3504 Adding Aseal documentation
  dev-docs/bidders/aseal.md
Labels: LGTM
