Repository prebid/prebid.github.io, pull requests merged in 2022-06, with the labels that each got.

#3804 AdYouLike BidderAdapter schain support
  dev-docs/bidders/adyoulike.md
Labels: LGTM

#3797 Zeta global ssp adapter docs
  dev-docs/bidders/zeta_global_ssp.md
Labels: LGTM, not merged yet

#3794 Updated docs for Kobler adapter
  dev-docs/bidders/kobler.md
Labels: LGTM, not merged yet

#3781 Update stroeerCore.md
  dev-docs/bidders/stroeerCore.md
Labels: LGTM, not merged yet

#3810 Magnite adapter GVL ID update
  dev-docs/bidders/slimcut.md
  dev-docs/bidders/spotx.md
  dev-docs/bidders/telaria.md
Labels: LGTM, not merged yet

#3799 Prebid 7: update docs on refererInfo, publisherDomain
  dev-docs/bidder-adaptor.md
  dev-docs/bidders/kobler.md
  dev-docs/modules/enrichmentFpdModule.md
  dev-docs/plugins/bc/bc-prebid-plugin-prebid-options.md
  dev-docs/plugins/cross-player-prebid-component/cross-player-config.md
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM, Pending Next Major Release

#3813 Removed akamaiUserID documentation
  dev-docs/modules/userId.md
Labels: LGTM, Pending Next Major Release

#3807 feat: updated insticator.md
  dev-docs/bidders/insticator.md
Labels: LGTM, Pending PBJS Release

#3809 Updated merkleId parameters
  dev-docs/modules/userId.md
Labels: LGTM

#3765 Remove adlive bidder (PBJS 7)
  dev-docs/bidders/adlive.md
Labels: Pending Next Major Release

#3779 Create pb7-notes.md
  dev-docs/bidders/appnexus.md
  dev-docs/bidders/colossus.md
  dev-docs/bidders/kargo.md
  dev-docs/bidders/rubicon.md
  dev-docs/bidders/sharethrough.md
  dev-docs/bidders/ttd.md
  dev-docs/pb7-notes.md
Labels: Pending Next Major Release

#3812 feature/blueconicRtdProvider
  dev-docs/modules/blueconicRtdProvider.md
Labels: LGTM

#3727 TrustX: make trustx as alias of gridBidAdapter
  dev-docs/bidders/adlivetech.md
  dev-docs/bidders/grid.md
  dev-docs/bidders/gridNM.md
  dev-docs/bidders/playwire.md
  dev-docs/bidders/trustx.md
  dev-docs/bidders/trustxstandalone.md
Labels: LGTM, Pending Next Major Release

#3822 Update consentManagementUsp.md
  dev-docs/modules/consentManagementUsp.md
Labels: Pending Next Major Release

#3762 Prebid 7: update docs for `allowAlternateBidderCodes` and related fields
  dev-docs/bidder-adaptor.md
  dev-docs/publisher-api-reference/bidderSettings.md
Labels: needs work, Pending Next Major Release

#3619 NextRoll ID: Remove NextRoll ID module docs
  dev-docs/bidders/openx.md
  dev-docs/bidders/synacormedia.md
  dev-docs/modules/userId.md
  download.md
Labels: Pending Next Major Release

#3780 Change storagemanager default access
  dev-docs/publisher-api-reference/bidderSettings.md
Labels: Pending Next Major Release

#3749 Prebid 7: consent management - remove references to TCFv1 and update examples to use TCFv2
  dev-docs/modules/consentManagement.md
Labels: LGTM

#3816 AdUp Technology Adapter update docs
  dev-docs/bidders/aduptech.md
Labels: LGTM

#3826 IX Bid Adapter: Outstream Floating Support
  dev-docs/bidders/ix.md
Labels: LGTM

#3823 Prebid 7: update docs related to first-party data
  dev-docs/add-rtd-submodule.md
  dev-docs/bidder-adaptor.md
  dev-docs/modules/enrichmentFpdModule.md
  dev-docs/modules/validationFpdModule.md
  dev-docs/publisher-api-reference/requestBids.md
  dev-docs/publisher-api-reference/setConfig.md
  features/firstPartyData.md
Labels: LGTM

#3854 Update huaweiads.md
  dev-docs/bidders/huaweiads.md
Labels: LGTM, not merged yet

#3711 Add new Adapter: TrafficGate
  dev-docs/bidders/trafficgate.md
Labels: LGTM, Pending PBJS Release

#3819 Add AudienceOne ID and modify name to YieldOne from YIELDONE in yieldone.md
  dev-docs/bidders/yieldone.md
Labels: LGTM, not merged yet

#3814 Alkimi bid adapter: added features
  dev-docs/bidders/alkimi.md
Labels: LGTM

#3844 add finative Adapter
  dev-docs/bidders/finative.md
Labels: Pending PBJS Release

#3839 Update gumgum prebid docs
  dev-docs/bidders/gumgum.md
Labels: LGTM, not merged yet

#3827 idx bidder adapter docs
  dev-docs/bidders/idx.md
Labels: question, LGTM

#3825 Dianomi bid adapter: new bid adapter
  dev-docs/bidders/dianomi.md
Labels: LGTM, not merged yet

#3815 Criteo - State more explicitly that our bidder automatically includes our id module features
  dev-docs/bidders/criteo.md
Labels: LGTM, Pending PBJS Release

#3811 Lasso bid adapter
  dev-docs/bidders/lasso.md
Labels: LGTM, Pending PBJS Release

#3763 Sspbc adapter
  dev-docs/bidders/sspBC.md
Labels: LGTM

#3803 PBS auction endpoint: ext.prebid.targeting
  prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
Labels: LGTM

#3808 New doc for Shinez Prebid adapter
  dev-docs/bidders/shinez.md
Labels: LGTM, not merged yet

#3831 IX Bid Adapter: Documentation for Native Support
  dev-docs/bidders/ix.md
Labels: LGTM, Pending PBJS Release

#3836 OpenX Bid Adapter: update docs with video changes and adapter specifics
  dev-docs/bidders/openx.md
Labels: LGTM

#3835 Adnuntius Header Bidder: Added information about first party data.
  dev-docs/bidders/adnuntius.md
Labels: question, LGTM
