Repository prebid/prebid.github.io, pull requests merged in 2023-02, with the labels that each got.

#4309 Adprime Adapter: text edit only
  dev-docs/bidders/adprime.md
Labels: LGTM

#4322 Zeta global ssp bidfloor
  dev-docs/bidders/zeta_global_ssp.md
Labels: LGTM

#4325 appnexus bidder docs - remove duplicate param
  dev-docs/bidders/appnexus.md
Labels: LGTM

#4235 Taboola Bid Adapter: Supporting First Party Data
  dev-docs/bidders/taboola.md
Labels: LGTM, Pending PBJS Release

#4300 Prebid.js: update docs for `bidCpmAdjustment` and `inverseCpmAdjutment`
  dev-docs/publisher-api-reference/bidderSettings.md
Labels: LGTM, not merged yet

#4317 Adkernel: consistent zoneId parameter type across aliases
  dev-docs/bidders/adbite.md
  dev-docs/bidders/adkernel.md
  dev-docs/bidders/adsolut.md
  dev-docs/bidders/audiencemedia.md
  dev-docs/bidders/bcm.md
  dev-docs/bidders/headbidding.md
  dev-docs/bidders/houseofpubs.md
  dev-docs/bidders/rtbdemand_com.md
  dev-docs/bidders/sonic_twist.md
  dev-docs/bidders/waardex_ak.md
Labels: LGTM

#4308 Publisher API Reference: Added doc page for pbjs.aliasRegistry
  dev-docs/publisher-api-reference/aliasRegistry.md
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM

#4236 Fix rise docs & add is_wrapper private param
  dev-docs/bidders/rise.md
Labels: LGTM, Pending PBJS Release

#4345 Update ConnectId example value
  dev-docs/modules/userId.md
Labels: LGTM

#4338 update amxid documentation
  dev-docs/modules/userId.md
  dev-docs/modules/userid-submodules/amxrtb.md
Labels: LGTM

#4342 Updating EMXDigital Doc to include floors support
  dev-docs/bidders/emx_digital.md
Labels: LGTM

#4339 appnexus bidder doc - userid update
  dev-docs/bidders/appnexus.md
Labels: LGTM

#4304 Feature/arcspan rtd provider
  dev-docs/modules/arcspanRtdProvider.md
Labels: LGTM

#4349 Remove google fonts
  _includes/head--common.html
Labels: LGTM

#4281 docs(module): MinuteMediaPlus bid adapter dev-docs
  dev-docs/bidders/minutemediaplus.md
Labels: LGTM

#4282 Documentation for Adsinteractive Adapter
  dev-docs/bidders/adsinteractive.md
Labels: LGTM

#4289 SmileWanted Adapter : Update support of eids
  dev-docs/bidders/smilewanted.md
Labels: LGTM

#4343 Update ramp.md
  dev-docs/modules/userid-submodules/ramp.md
Labels: LGTM

#4351 Mobile: various clarification info
  prebid-mobile/pbm-api/android/code-integration-android.md
  prebid-mobile/pbm-api/android/pbm-targeting-params-android.md
  prebid-mobile/pbm-api/ios/pbm-targeting-ios.md
Labels: LGTM

#4347 Add new google analytics v4 tag
  _includes/footer.html
Labels: LGTM

#4293 Seller Defined Audience Support for Sirdata RTD Module
  dev-docs/modules/sirdataRtdProvider.md
Labels: LGTM

#4288 Limelight Digital Bid Adapter: add custom targeting fields, rename iionads title to iion
  dev-docs/bidders/iionads.md
  dev-docs/bidders/limelightDigital.md
Labels: LGTM

#4336 appnexus bid params - underscore format update
  dev-docs/bidders/appnexus.md
Labels: LGTM

#4271 Seedtag bid adapter - Add GPP consent
  dev-docs/bidders/seedtag.md
Labels: LGTM

#4265 smartx Bid Adapter: add support for sitekey
  dev-docs/bidders/smartx.md
Labels: LGTM

#4234 Adkernel: Documenting Bidbuddy
  dev-docs/bidders/bidbuddy.md
Labels: LGTM

#4181 Add docs for Scattered bid adapter
  dev-docs/bidders/scattered.md
Labels: LGTM

#4280 AIDEM Bidder Adapter: Updated Banner/Video AdUnit examples and GDPR TCF Support feature
  dev-docs/bidders/aidem.md
Labels: LGTM

#4267 BrightcomSSP bid adapter: add new bidder page
  dev-docs/bidders/brightcomssp.md
Labels: LGTM

#4244 Feature/neuwo rtd provider
  dev-docs/modules/neuwoRtdProvider.md
Labels: LGTM

#4238 Logan Bid Adapter: updating removed adapter
  dev-docs/bidders/logan.md
Labels: LGTM

#4263 Outbrain: added video support and example
  dev-docs/bidders/outbrain.md
Labels: LGTM

#4242 CWire: Introduce prebid server adapter
  dev-docs/bidders/cwire.md
Labels: LGTM

#4126 New Adapter: Kivi
  dev-docs/bidders/kiviads.md
Labels: LGTM

#4264 New Adapter: Definemedia
  dev-docs/bidders/definemedia.md
Labels: LGTM

#4039 Added pbs support to Brave doc
  dev-docs/bidders/brave.md
Labels: LGTM

#4269 Fix code example for getBidRequestData in add-rtb-submodule
  dev-docs/add-rtd-submodule.md
Labels: LGTM

#4329 Taboola Bid Adapter : support native in prebid server
  dev-docs/bidders/taboola.md
Labels: LGTM

#4373 Mobile add test ad unit configs
  prebid-mobile/pbm-api/android/code-integration-android.md
  prebid-mobile/pbm-api/ios/code-integration-ios.md
Labels: LGTM

#4365 Updated Livewrapped Bid Adapter documentation
  dev-docs/bidders/livewrapped.md
Labels: LGTM

#4376 PBJS: Document `adUnit.bids[].ortb2Imp` and `module`
  dev-docs/adunit-reference.md
  dev-docs/modules/prebidServer.md
Labels: LGTM

#4378 add EUC endpoint for Algorix
  dev-docs/bidders/algorix.md
Labels: LGTM

#4327 New Adapter: Optidigital
  dev-docs/bidders/optidigital.md
Labels: LGTM

#4361 Add GPP Support to KueezRTB Bid Adapter
  dev-docs/bidders/kueezrtb.md
Labels: LGTM, Pending PBJS Release

#4380 NeuwoRTDProvider: docs: Overview, apiUrl
  dev-docs/modules/neuwoRtdProvider.md
Labels: LGTM

#4381 Update unruly.md
  dev-docs/bidders/unruly.md
Labels: LGTM

#4379 Adagio: add user-sync config recommends
  dev-docs/bidders/adagio.md
Labels: LGTM

#4371 Update smaato.md to indicate gpp support
  dev-docs/bidders/smaato.md
Labels: LGTM

#4367 Adagio: update doc video params
  dev-docs/bidders/adagio.md
Labels: LGTM

#4346 Admedia Adapter Doc
  dev-docs/bidders/admedia.md
Labels: LGTM

#4364 Eps update analytics docs
  dev-docs/analytics/epsilon.md
Labels: LGTM

#4360 Video docs updates
  _data/sidebar.yml
  _includes/head--common.html
  _includes/video/pb-is-app.html
  _includes/video/pb-is-bc.html
  _includes/video/pb-is-br.html
  _includes/video/pb-is-jw01.html
  _includes/video/pb-is-jw02.html
  _includes/video/pb-is-ol.html
  _includes/video/pb-is-vjs.html
  _includes/video/pb-lf-fw.html
  _includes/video/pb-os-dfp.html
  _includes/video/pb-os-nas-renderer.html
  _includes/video/pb-os-nas.html
  _includes/video/pbs-oy.html
  _layouts/video_sample.html
  dev-docs/show-video-with-a-dfp-video-tag.md
  examples/video/crossplayer/flowplayer/pb-cp-flowplayer.html
  examples/video/crossplayer/jwplayer/pb-cp-jwplayer.html
  examples/video/crossplayer/kaltura/pb-cp-kaltura.html
  examples/video/crossplayer/videojs/pb-cp-videojs.html
  examples/video/index.md
  examples/video/instream/adplayerpro/pb-ve-adplayerpro.html
  examples/video/instream/akamai/pb-ve-amp.html
  examples/video/instream/brid/pb-ve-brid.html
  examples/video/instream/brightcove/pb-ve-brightcove.html
  examples/video/instream/flowplayer/pb-ve-flowplayer.html
  examples/video/instream/jwplayer/pb-ve-jwplayer-hosted.html
  examples/video/instream/jwplayer/pb-ve-jwplayer-platform.html
  examples/video/instream/kaltura/pb-ve-kaltura.html
  examples/video/instream/ooyala/pb-ve-ooyala.html
  examples/video/instream/radiant/pb-ve-radiant.html
  examples/video/instream/videojs/pb-ve-videojs.html
  examples/video/long-form/pb-ve-lf-freewheel.html
  examples/video/outstream/basic-ima.html
  examples/video/outstream/pb-ve-outstream-dfp.html
  examples/video/outstream/pb-ve-outstream-no-server-specify-renderer.html
  examples/video/outstream/pb-ve-outstream-no-server.html
  examples/video/server/brid/pbs-ve-brid.html
  examples/video/server/jwplayer/pbs-ve-jwplayer-hosted.html
  examples/video/server/jwplayer/pbs-ve-jwplayer-platform.html
  examples/video/server/kaltura/pbs-ve-kaltura.html
  examples/video/server/ooyala/pbs-ve-ooyala.html
  examples/video/server/radiant/pbs-ve-radiant.html
  examples/video/server/videojs/pbs-ve-videojs.html
  prebid-video/video-integrating-solo.md
Labels: LGTM
