Repository prebid/prebid.github.io, pull requests merged in 2023-11, with the labels that each got.

#4881 Add mediabrama.md
  dev-docs/bidders/mediabrama.md
Labels: LGTM, not merged yet

#4941 Connatix docs updated extra example
  dev-docs/bidders/connatix.md
Labels: needs work

#4948 Added agma analytics adapter
  dev-docs/analytics/agma.md
Labels: LGTM, not merged yet

#4947 New Adapter: bluesea.md
  dev-docs/bidders/bluesea.md
Labels: LGTM

#4871 Update teads documentation
  dev-docs/bidders/teads.md
Labels: LGTM

#4926 Impactify : Add informations on storage in documentations
  dev-docs/bidders/impactify.md
Labels: LGTM

#4935 GoldfishAdsRtdProvider: New Module
  dev-docs/modules/goldfishAdsRtdProvider.md
Labels: LGTM

#4936 Add SDK Renderer Info
  prebid-server/developers/add-new-bidder-java.md
Labels: LGTM

#4978 Update pb8-notes.md
  dev-docs/pb8-notes.md
Labels: LGTM

#4969 PBS Digital Out of Home - initial docs
  _data/sidebar.yml
  assets/images/flowcharts/prebid-server/pbs-basic-flow.png
  assets/images/flowcharts/prebid-server/pbs-dooh-flow.png
  prebid-server/overview/prebid-server-overview.md
  prebid-server/use-cases/pbs-dooh.md
Labels: LGTM

#4946 New Bidder Adapter - Adzymic Docs
  dev-docs/adzymic.md
Labels: not merged yet

#4922 Zeta Global SSP: update parameters for the bidder adapter
  dev-docs/bidders/zeta_global_ssp.md
Labels: LGTM, not merged yet

#4424 New Adapter: Axis
  dev-docs/bidders/axis.md
Labels: needs work

#4963 Download - Don't handle analytics modules separately
  assets/js/download.js
  download.md
Labels: LGTM

#4964 MSFT/Xandr updates
  _data/sidebar.yml
  adops/setting-up-prebid-with-the-appnexus-ad-server.md
  dev-docs/examples/use-prebid-with-appnexus-ad-server.md
Labels: LGTM

#4958 add adstir Bid Adapter
  dev-docs/bidders/adstir.md
Labels: LGTM

#4981 add indicue doc
  dev-docs/bidders/indiecue.md
Labels: LGTM, not merged yet

#4952 AsterioBid Analytics adapter
  dev-docs/analytics/asteriobid.md
Labels: not merged yet

#4954 New Adapter: oms
  dev-docs/bidders/oms.md
Labels: not merged yet

#4976 Update mediaTypes to include native
  dev-docs/bidders/sharethrough.md
Labels: LGTM, not merged yet
