Repository prebid/prebid.github.io, pull requests merged in 2023-07, with the labels that each got.

#4696 add gpp support to Consumable docs
  dev-docs/bidders/consumable.md
Labels: LGTM

#4629 Add Apester prebid js adapter doc
  dev-docs/bidders/apester.md
  dev-docs/bidders/evtech.md
  dev-docs/bidders/iionads.md
  dev-docs/bidders/limelightDigital.md
Labels: LGTM

#4655 weborama rtd submodule update doc to reflect fix in appnexus integration for v8
  dev-docs/modules/weboramaRtdProvider.md
Labels: needs work

#4704 pubmatic.md update for dctr parameter
  dev-docs/bidders/pubmatic.md
Labels: LGTM

#4710 IX Bid Adapter: Add 33Across to IX's list of userIds
  dev-docs/bidders/ix.md
Labels: LGTM

#4627 AIDEM Bid Adapter: added pbs
  dev-docs/bidders/aidem.md
Labels: LGTM, not merged yet

#4606 Trafficgate Bid Adapter: move to OpenRTB Converter
  dev-docs/bidders/trafficgate.md
Labels: LGTM, not merged yet

#4691 Update pubmatic.md: Add gpp support
  dev-docs/bidders/pubmatic.md
Labels: LGTM

#4682 imds: Add gpp_support for adapter
  dev-docs/bidders/imds.md
Labels: LGTM

#4671 GPP and COPPA support for Medianet Bidder Adapter
  dev-docs/bidders/medianet.md
Labels: question

#4726 Add note on legacy for kargo
  dev-docs/bidders/kargo.md
Labels: LGTM

#4724 Fix #4481 improve first party data docs
  features/firstPartyData.md
Labels: LGTM

#4719 appnexus bidder - update first party data note
  dev-docs/bidders/appnexus.md
Labels: LGTM

#4722 Add optional keys
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM

#4737 Adkernel: documenting gpp support
  dev-docs/bidders/adbite.md
  dev-docs/bidders/adkernel.md
  dev-docs/bidders/adliveconnect.md
  dev-docs/bidders/adomega.md
  dev-docs/bidders/adsolut.md
  dev-docs/bidders/audiencemedia.md
  dev-docs/bidders/bcm.md
  dev-docs/bidders/bidbuddy.md
  dev-docs/bidders/converge.md
  dev-docs/bidders/denakop.md
  dev-docs/bidders/didnadisplay.md
  dev-docs/bidders/displayioads.md
  dev-docs/bidders/engageadx.md
  dev-docs/bidders/ergadx.md
  dev-docs/bidders/felixads.md
  dev-docs/bidders/headbidding.md
  dev-docs/bidders/houseofpubs.md
  dev-docs/bidders/motionspots.md
  dev-docs/bidders/qortex.md
  dev-docs/bidders/rtbanalytica.md
  dev-docs/bidders/rtbdemand_com.md
  dev-docs/bidders/sonic_twist.md
  dev-docs/bidders/turktelekom.md
  dev-docs/bidders/unibots.md
  dev-docs/bidders/waardex_ak.md
Labels: LGTM

#4705 PulsePoint Bid Adapter: Doc update based on adapter updates
  dev-docs/bidders/pulsepoint.md
Labels: LGTM

#4730 Adkernel: documenting adpluto alias
  dev-docs/bidders/adpluto.md
Labels: LGTM

#4747 Add prebid 8 release notes
  prebid/prebidjsReleases.md
Labels: LGTM

#4731 Adkernel: documenting adpluto_dsp alias
  dev-docs/bidders/adpluto_dsp
Labels: LGTM

#4750 Fix HTML errors
  dev-docs/adunit-reference.md
  dev-docs/analytics-ga.md
Labels: LGTM

#4745 Added Native Support and Updated Outdated Support Flags
  dev-docs/bidders/vrtcal.md
Labels: LGTM

#4661 Yahoo bid adapter rebrand documentation
  dev-docs/bidders/yahooAdvertising.md
Labels: LGTM

#4672 New RTD Provider : A1Media
  dev-docs/modules/a1MediaRtdProvider.md
Labels: LGTM

#4680 add docs for Geolocation Module
  dev-docs/modules/geolocationRtdProvider.md
Labels: LGTM

#4699 Add SSMas BidAdapter docs
  dev-docs/bidders/ssmas.md
Labels: LGTM

#4700 GPP & COPPA support for 33across bidder adapter
  dev-docs/bidders/33across.md
Labels: LGTM

#4708 gothamads: add pbs support
  dev-docs/bidders/gothamads.md
Labels: LGTM

#4714 vox adapter add support schain, userid, floors module
  dev-docs/bidders/vox.md
Labels: LGTM

#4741 LiveIntent UserId module: magnite id documentation
  dev-docs/modules/userid-submodules/liveintent.md
Labels: LGTM

#4599 New Adapter: HypeLab
  dev-docs/bidders/hypelab.md
Labels: LGTM

#4687 OwnadX prebid server documentation
  dev-docs/bidders/ownadx.md
Labels: LGTM

#4681 New bidder adapter: Viant
  dev-docs/bidders/viant.md
Labels: LGTM

#4718 New Bid Adapter Docs: PubCircle
  dev-docs/bidders/pubcircle.md
Labels: LGTM

#4755 Change AdsInteractive documentation
  dev-docs/bidders/adsinteractive.md
Labels: LGTM
