Repository prebid/prebid.github.io, pull requests merged in 2023-08, with the labels that each got.

#4713 BidAdapter: Connatix Bid Adapter
  dev-docs/bidders/connatix.md
Labels: LGTM, not merged yet

#4760 screencore: new adapter
  dev-docs/bidders/screencore.md
Labels: LGTM, not merged yet

#4736 Update PBS TPMN
  dev-docs/bidders/tpmn.md
Labels: LGTM, not merged yet

#4716 Indicate that GPP is supported in the Adagio adapter
  dev-docs/bidders/adagio.md
Labels: LGTM, not merged yet

#4707 Initial commit for docs of autoamatad analytics adapter
  dev-docs/analytics/automatad.md
Labels: LGTM, not merged yet

#4675 Update userId.md to document scenario when user id submodule populate…
  dev-docs/modules/userId.md
Labels: needs work

#4498 Add magnite id to examples
  dev-docs/modules/userid-submodules/liveintent.md
Labels: LGTM, has conflicts

#4767 documentation for the professor prebid user sync network inspector tool
  assets/images/tools/professor-prebid-11.png
  assets/images/tools/professor-prebid-12.png
  assets/images/tools/professor-prebid-13.png
  tools/professor-prebid.md
Labels: needs work

#4788 documentation for the prebid.js version analyzer tool in prof prebid
  assets/images/tools/professor-prebid-14.png
  tools/professor-prebid.md
Labels: LGTM

#4792 LiveIntent UserId module: index id documentation
  dev-docs/modules/userid-submodules/liveintent.md
Labels: LGTM

#4806 Fix scetion typo in ac-quebec.md
  features/ac-quebec.md
Labels: LGTM

#4763 PrebidMobile: update Initialize SDK section in code-integration-ios
  prebid-mobile/pbm-api/ios/code-integration-ios.md
Labels: LGTM, on hold

#4807 Update bidder page to indicate GPP support for Cadent Aperture MX Adapter
  dev-docs/bidders/cadent_aperture_mx.md
Labels: LGTM

#4785 LM KiviAds prebid server adapter docs
  dev-docs/bidders/lm_kiviads.md
Labels: LGTM

#4757 Add new adapter doc for liftoff
  dev-docs/bidders/liftoff.md
Labels: LGTM

#4748 Silverpush: added Prebid Server adapter.
  dev-docs/bidders/silverpush.md
Labels: LGTM

#4789 Update sharethrough.md
  dev-docs/bidders/sharethrough.md
Labels: LGTM

#4798 Update bidder-adaptor.md to include topics response
  dev-docs/bidder-adaptor.md
Labels: LGTM

#4801 AMX RTB: indicate ortb blocking support, add bidder settings section
  dev-docs/bidders/amx-server.md
  dev-docs/bidders/amx.md
Labels: LGTM

#4804 added a prebid server params section to the Sonobi bidder docs
  dev-docs/bidders/sonobi.md
Labels: LGTM

#4814 Adprime adapter: fix biddercode
  dev-docs/bidders/adprime.md
Labels: LGTM

#4771 No bid version 1.4.0
  dev-docs/bidders/nobid.md
Labels: not merged yet

#4817 Adkernel: documenting headbidder.net alias
  dev-docs/bidders/headbidder.md
Labels: LGTM, Pending PBJS Release

#4811 PubMaticBidAdapter - Updated bidder parameters document for lat & lon
  dev-docs/bidders/pubmatic.md
Labels: LGTM, Pending PBJS Release

#4639 New Bidder Doc: Preciso bidder doc added
  dev-docs/bidders/preciso.md
Labels: LGTM

#4720 Add Relay Bid Adapter doc.
  dev-docs/bidders/relay.md
Labels: needs work

#4821 New NoBid Analytics Adapter 1.0.0
  dev-docs/analytics/nobid.md
Labels: LGTM

#4770 Move send all bids section to bottom of page
  _layouts/bidder.html
Labels: LGTM
