Repository prebid/prebid.github.io, pull requests merged in 2023-04, with the labels that each got.

#4430 Adagio: Add documentation for splitKeyword and dataLayer params
  dev-docs/bidders/adagio.md
Labels: LGTM, not merged yet

#4455 Smaato: accept geolocation data also from ortb2
  dev-docs/bidders/smaato.md
Labels: LGTM

#4452 Novatiq UserID Module: update docs to make it easier for clients
  dev-docs/modules/userid-submodules/novatiq.md
Labels: LGTM

#4470 ZetaGlobalSsp adapter: tagid in docs
  dev-docs/bidders/zeta_global_ssp.md
Labels: LGTM

#4466 PBJS: document new `storageAllowed` options
  dev-docs/publisher-api-reference/bidderSettings.md
Labels: LGTM

#4465 Updated doc for Vidoomy Schain module
  dev-docs/bidders/vidoomy.md
Labels: LGTM

#4427 add greenbids analytics documentation
  dev-docs/analytics/greenbids.md
Labels: LGTM, not merged yet

#4478 Triplelift: Update video parameters requirement
  dev-docs/bidders/triplelift.md
Labels: LGTM

#4480 Criteo: update doc
  dev-docs/bidders/criteo.md
Labels: LGTM

#4483 Adman Adapter: text edit only
  dev-docs/bidders/adman.md
Labels: LGTM

#4456 Updated documentation for Yahoo ConnectID UserID module
  dev-docs/modules/userid-submodules/yahoo.md
Labels: LGTM

#4467 PBJS: document new option for RTD submodules
  dev-docs/add-rtd-submodule.md
Labels: LGTM

#4437 Concert Bid Adapter: Indicate GPP support
  dev-docs/bidders/concert.md
Labels: LGTM

#4468 Document rewarded display declaration
  features/firstPartyData.md
Labels: LGTM

#4453 Documentation for Batch Video Cache Requests
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM

#4461 Update KueezRTB and Kueez docs
  dev-docs/bidders/kueez.md
  dev-docs/bidders/kueezrtb.md
Labels: LGTM

#4479 Yandex adapter: add pbs support and add native media_type
  dev-docs/bidders/yandex.md
Labels: LGTM, not merged yet

#4440 appnexus - change fpd flag
  dev-docs/bidders/appnexus.md
Labels: on hold

#4436 9Dots Media adapter
  dev-docs/bidders/9dotsmedia.md
Labels: LGTM, not merged yet

#4428 PubWise Support PBS
  dev-docs/bidders/pwbid.md
Labels: LGTM, not merged yet

#4422 ShowHeroes Bid Adapter: update documentation
  dev-docs/bidders/showheroes-bs.md
Labels: not merged yet

#4421 New Adapter: Evolution Technologies
  dev-docs/bidders/evtech.md
  dev-docs/bidders/iionads.md
  dev-docs/bidders/limelightDigital.md
Labels: not merged yet

#4417 DSPx docs update
  dev-docs/bidders/dspx.md
Labels: LGTM, not merged yet

#4394 BEdigitech Bid Adapter: New Adapter
  dev-docs/bidders/bedigitech.md
Labels: LGTM, not merged yet

#4363 Mobile: Restore the description of Prebid SDK utilization with 3rd party ad server
  prebid-mobile/modules/rendering/android-sdk-integration-pb.md
  prebid-mobile/modules/rendering/ios-sdk-integration-pb.md
  prebid-mobile/pbm-api/android/android-sdk-integration-gam-original-api.md
Labels: needs work, on hold

#4493 Updated docs for Vidoomy blocking supported
  dev-docs/bidders/vidoomy.md
Labels: LGTM, not merged yet

#4474 Updated documentation for Vidoomy bidfloor and userId module
  dev-docs/bidders/vidoomy.md
Labels: LGTM, not merged yet
