Repository prebid/prebid.github.io, pull requests merged in 2023-01, with the labels that each got.

#4216 consentManagement GPP module docs
  dev-docs/bidders/appnexus.md
  dev-docs/modules/consentManagementGpp.md
  features/firstPartyData.md
Labels: LGTM

#4058 Viously Bid Adapter : New Adapter
  dev-docs/bidders/viously.md
Labels: LGTM

#4092 PBJS: document new `genericAnalyticsAdapter` module
  dev-docs/analytics/generic.md
  dev-docs/modules/gdprEnforcement.md
  dev-docs/modules/genericAnalyticsAdapter.md
Labels: LGTM

#4137 AIDEM Bid Adapter PR dev-docs
  dev-docs/bidders/aidem.md
Labels: LGTM

#4140 Nexx360 prebid adapter update
  dev-docs/bidders/nexx360.md
Labels: LGTM

#4173 Bidstack: Add optional Placement ID field
  dev-docs/bidders/bidstack.md
Labels: LGTM

#4204 Kueez RTB: Added video media type
  dev-docs/bidders/kueezrtb.md
Labels: LGTM

#4212 Rubicon: new param
  dev-docs/bidders/rubicon.md
Labels: LGTM

#4273 VISX: Update type support for uid
  dev-docs/bidders/visx.md
Labels: LGTM

#4250 Adagio: update bidAdapter params description
  dev-docs/bidders/adagio.md
Labels: LGTM, Pending PBJS Release

#4192 Updated setConfig doc page to include details about optional category targeting
  dev-docs/publisher-api-reference/setConfig.md
Labels: question

#4220 Appush Bid Adapter: init
  dev-docs/bidders/appush.md
Labels: LGTM, not merged yet

#4285 Appush Bid Adapter: doc edit only
  dev-docs/bidders/appush.md
Labels: LGTM

#4287 Update ats.md
  dev-docs/analytics/ats.md
Labels: LGTM

#4290 Updated ix.md on how to enable the Index adapter
  dev-docs/bidders/ix.md
Labels: LGTM

#4291 IX Bid Adapter: add gpp support flag to ix bidder doc
  dev-docs/bidders/ix.md
Labels: LGTM

#4266 Taboola Bidder Adapter: Support Prebid Server New Adapter
  dev-docs/bidders/taboola.md
Labels: LGTM

#4279 Create admixeradx.md + update admixer.md with floor support
  dev-docs/bidders/admixer.md
  dev-docs/bidders/admixeradx.md
Labels: LGTM

#4299 MobileFuse Adapter: native support added to docs
  dev-docs/bidders/mobilefuse.md
Labels: LGTM

#3497 Docs for native openRTB
  dev-docs/adunit-reference.md
  dev-docs/bidder-adaptor.md
  prebid/native-implementation-legacy.md
  prebid/native-implementation.md
Labels: LGTM

#4278 Add Adriver ID User ID sub-module
  dev-docs/modules/userId.md
  dev-docs/modules/userid-submodules/adriver.md
Labels: LGTM
