Repository prebid/prebid.github.io, pull requests merged in 2023-10, with the labels that each got.

#4904 Concert: Add supported userIds
  dev-docs/bidders/concert.md
Labels: LGTM, Pending PBJS Release

#4892 Qortex RealTime Data Module Documentation
  dev-docs/modules/qortexRtdProvider.md
Labels: needs work

#4898 Smartyads/add_prebid_server_params
  dev-docs/bidders/smartyads.md
Labels: needs work

#4829 Lm kiviads
  dev-docs/bidders/lm_kiviads.md
Labels: LGTM

#4907 NoBid Analytics: Enable download
  dev-docs/analytics/nobid.md
Labels: LGTM

#4839 Delete removed aliases docs
  dev-docs/bidders/bidsxchange.md
  dev-docs/bidders/pgam.md
  dev-docs/bidders/vidcrunchllc.md
Labels: question

#4915 Sovrn: make minduration recommended
  dev-docs/bidders/sovrn.md
Labels: LGTM

#4912 update smartx documentation for support pbs
  dev-docs/bidders/smartx.md
Labels: LGTM

#4925 update docs to create an alias using new pattern
  prebid-server/developers/add-new-bidder-go.md
Labels: LGTM

#4910 Add Pubmatic And Openx Doc
  dev-docs/modules/userid-submodules/liveintent.md
Labels: LGTM

#4929 Mobile extend api for gpid and events
  prebid-mobile/modules/rendering/android-sdk-integration-pb.md
  prebid-mobile/modules/rendering/ios-sdk-integration-pb.md
  prebid-mobile/pbm-api/android/android-sdk-integration-gam-original-api.md
  prebid-mobile/pbm-api/ios/ios-sdk-integration-gam-original-api.md
Labels: LGTM

#4864 New adapter Edge226
  dev-docs/bidders/edge226.md
Labels: question, LGTM, not merged yet

#4869 Create Android Plugin Renderer documentation
  _data/sidebar.yml
  assets/images/prebid-mobile/prebid-plugin-renderer-ad-view-injection.png
  assets/images/prebid-mobile/prebid-plugin-renderer-event-listeners.png
  assets/images/prebid-mobile/prebid-plugin-renderer.png
  prebid-mobile/pbm-api/android/pbm-plugin-renderer.md
  prebid-mobile/prebid-mobile.md
Labels: Pending Prebid Module Release

#4897 LemmaDigital Adapter: pbs support
  dev-docs/bidders/lemmadigital.md
Labels: LGTM, not merged yet

#4917 Sparteo Bid Adapter: Add Sparteo documentation
  dev-docs/bidders/sparteo.md
Labels: LGTM, not merged yet

#4893 Update oxxionRtdProvide.md
  dev-docs/modules/oxxionRtdProvide.md
Labels: needs work

#4902 IQX bidder adapter docs init
  dev-docs/bidders/iqx.md
Labels: LGTM, not merged yet
