Repository prebid/prebid.github.io, pull requests merged in 2023-09, with the labels that each got.

#4603 Draft: Add docs for EUID module.
  dev-docs/modules/userid-submodules/euid.md
  dev-docs/modules/userid-submodules/unified2.md
Labels: LGTM

#4823 feat: update pangle md
  dev-docs/bidders/pangle.md
Labels: LGTM, Pending PBJS Release

#4837 Boldwin Adapter: gpp support
  dev-docs/bidders/boldwin.md
Labels: LGTM

#4859 Boldwin: update prebid documentation
  dev-docs/bidders/boldwin.md
Labels: LGTM

#4701 YieldloveBidAdapter: Release
  dev-docs/bidders/yieldlove.md
Labels: LGTM, not merged yet

#4827 Update flipp.md - add pbjs adapter
  dev-docs/bidders/flipp.md
Labels: LGTM

#4860 OptimeraRTD: Adding apiVersion parameter description.
  dev-docs/modules/optimeraRtdProvider.md
Labels: LGTM

#4835 LiveIntent UserId module: Adjust ajax timeout doc
  dev-docs/modules/userid-submodules/liveintent.md
Labels: LGTM

#4848 update mabidder.md documetation support pbs
  dev-docs/bidders/mabidder.md
Labels: LGTM

#4866 Update 33across.md to reflect country support
  dev-docs/modules/userid-submodules/33across.md
Labels: LGTM

#4847 id5 id module minor text updates
  dev-docs/modules/userid-submodules/id5.md
Labels: LGTM

#4833 Experian rtd documentation
  dev-docs/modules/experianRtdProvider.md
Labels: LGTM

#4810 Bid adapter PGAMSSP: new adapter
  dev-docs/bidders/pgamssp.md
Labels: LGTM

#4862 Bidgency Adapter: Added aso alias code
  dev-docs/bidders/bidgency.md
Labels: LGTM

#4861 Bcmint Adapter: Added aso alias code
  dev-docs/bidders/bcmint.md
Labels: LGTM

#4822 New adapter: Appstock
  dev-docs/bidders/appstock.md
Labels: LGTM

#4812 Bematterfull bid adapter: init dev-docs
  dev-docs/bidders/bematterfull
Labels: LGTM

#4795 Adquery: added info about supporting pbs
  dev-docs/bidders/adquery.md
Labels: LGTM

#4778 Bliink Bid Adapter Doc - Optional video url
  dev-docs/bidders/bliink.md
Labels: LGTM

#4836 AdagioAnalyticsAdapter: update doc
  dev-docs/analytics/adagio.md
Labels: LGTM

#4842 Update ix.md
  dev-docs/bidders/ix.md
Labels: LGTM

#4858 OptidigitalBidAdapter: Adding userId module, updating User Sync information
  dev-docs/bidders/optidigital.md
Labels: LGTM

#4844 Update eplanning.md
  dev-docs/bidders/eplanning.md
Labels: LGTM

#4853 Update sharethrough.md
  dev-docs/bidders/sharethrough.md
Labels: LGTM

#4843 Update ix-server.md
  dev-docs/bidders/ix-server.md
Labels: LGTM

#4850 New adapter: GreedyGame
  dev-docs/bidders/greedygame.md
Labels: LGTM

#4855 New Bid Adapter : AdFusion
  dev-docs/adfusion.md
Labels: LGTM

#4876 JS gdprEnforcement: document new transmitPreciseGeo, eidsRequireP4consent config
  dev-docs/modules/gdprEnforcement.md
Labels: LGTM

#4875 Prebid.js: document new `gppControl_usstates` module
  dev-docs/modules/gppControl_usnat.md
  dev-docs/modules/gppControl_usstates.md
Labels: LGTM

#4894 Update Viant as a Prebid member
  dev-docs/bidders/viant.md
Labels: LGTM

#4895 Update viant.md - update contact information in md file
  dev-docs/bidders/viant.md
Labels: LGTM

#4891 wordsmithing gdprEnforcement
  dev-docs/modules/gdprEnforcement.md
Labels: LGTM

#4896 AcuityAds Bid Adapter: add gpp support
  dev-docs/bidders/acuityads.md
Labels: LGTM

#4887 Mobfox Adapter: gpp support
  dev-docs/bidders/mobfoxpb.md
Labels: LGTM

#4813 IlluminBidAdapter
  dev-docs/bidders/illumin.md
Labels: LGTM

#4899 Update viant.md - update schain support parameter
  dev-docs/bidders/viant.md
Labels: LGTM

#4890 Integr8 Bid Adapter: added optional parameter
  dev-docs/bidders/integr8.md
Labels: LGTM

#4900 PBS-Java module: Added get CPU function
  prebid-server/developers/add-a-module-java.md
Labels: LGTM
