Repository prebid/prebid.github.io, pull requests merged in 2023-12, with the labels that each got.

#5005 Add gvl_id to vox adapter
  dev-docs/bidders/vox.md
Labels: LGTM

#4826 Shinez RTB bid adapter
  dev-docs/bidders/shinezRtb.md
Labels: LGTM

#5009 MinuteMedia Bid Adapter - Support Currency
  dev-docs/bidders/minutemedia.md
Labels: LGTM

#5008 Rise Bid Adapter - Supporting currency bidder param
  dev-docs/bidders/rise.md
Labels: LGTM

#4998 Embi media bidder adapter
  dev-docs/bidders/embimedia.md
Labels: LGTM

#5028 DXKulture - Updating docs details
  dev-docs/bidders/dxkulture.md
Labels: LGTM

#4994 OpenRTB 2.5 supported parameters
  dev-docs/bidders/nextMillennium.md
Labels: LGTM

#4977 Unruly: FPD and Protected Audience Support
  dev-docs/bidders/unruly.md
Labels: LGTM

#5013 add event bidAccepted in event slisting
  dev-docs/publisher-api-reference/getEvents.md
Labels: LGTM

#5046 Update ix.md
  dev-docs/bidders/ix.md
Labels: LGTM

#5045 Update ix-server.md
  dev-docs/bidders/ix-server.md
Labels: needs work

#4949 feature: Add ExcludeBidders from scan config and Analytic tags for Confiant Ad Quality module docs
  prebid-server/pbs-modules/confiant-ad-quality.md
Labels: LGTM, not merged yet
