Repository prebid/prebid.github.io, pull requests merged in 2023-06, with the labels that each got.

#4527 AdHash bid adapter changes
  dev-docs/bidders/adhash.md
Labels: LGTM, not merged yet

#4543 Xeworks adapter: pbs support added
  dev-docs/bidders/xe.md
Labels: not merged yet

#4583 Sharethrough - Support native
  dev-docs/bidders/sharethrough.md
Labels: LGTM, not merged yet

#4601 New adapter: Uol as an AppNexus alias
  dev-docs/bidders/uol.md
Labels: Pending PBJS Release

#4582 Yahoo ID: ConnectId auto generated puid and storage updates.
  dev-docs/modules/userid-submodules/yahoo.md
Labels: LGTM, not merged yet

#4609 FreeWheel SSP Adapter: add bidder params
  dev-docs/bidders/freewheelssp.md
Labels: question

#4614 Unnique enable_download flag in zeusPrimeRtdProvider.md
  dev-docs/modules/zeusPrimeRtdProvider.md
Labels: bug

#4604 Mobile - additional info
  prebid-mobile/modules/rendering/android-sdk-integration-gam.md
  prebid-mobile/modules/rendering/android-sdk-integration-pb.md
  prebid-mobile/pbm-api/android/code-integration-android.md
  prebid-mobile/prebid-mobile-getting-started.md
Labels: not merged yet

#4501 Prebid.js: activity controls
  dev-docs/activity-controls.md
  dev-docs/faq.md
  dev-docs/publisher-api-reference/setConfig.md
Labels: not merged yet

#4594 Add Eskimi adapter video support documentation
  dev-docs/bidders/eskimi.md
Labels: LGTM, not merged yet

#4619 Remove duplicate meta tags for viously
  dev-docs/bidders/viously.md
Labels: bug

#4621 minutemediaplus: added gpp_supported
  dev-docs/bidders/minutemediaplus.md
Labels: LGTM

#4622 vidazooBidAdapter: gpp_supported
  dev-docs/bidders/vidazoo.md
Labels: LGTM

#4485 Add FreePass IdSystem Docs
  dev-docs/modules/userId.md
  dev-docs/modules/userid-submodules/freepass.md
Labels: LGTM

#4598 remove groupm bidder
  dev-docs/bidders/groupm.md
Labels: LGTM

#4579 StroeerCore Bid Adapter: add price floor support
  dev-docs/bidders/stroeerCore.md
Labels: LGTM

#4578 epsilon branding for conversant
  dev-docs/analytics/epsilon.md
Labels: LGTM

#4544 init motorik adapter doc
  dev-docs/bidders/motorik.md
Labels: needs work

#4521 New Adapter: Conceptx
  dev-docs/bidders/conceptx.md
Labels: LGTM, not merged yet

#4519 growthCodeRtdProvider Docs
  dev-docs/modules/growthCodeRtdProvider.md
Labels: LGTM, not merged yet

#4642 marking mass as deprecated
  dev-docs/modules/mass.md
Labels: Pending Next Major Release

#4636 Aso Bid Adapter: documenting bidgency alias
  dev-docs/bidders/bidgency.md
Labels: LGTM

#4631 Rise - add PBS support documentation
  dev-docs/bidders/rise.md
Labels: LGTM

#4633 Cadent Aperture MX: rename emx to Cadent Aperture MX
  dev-docs/bidders/cadent_aperture_mx.md
Labels: LGTM

#4625 Add Pubtech Bidder docs
  dev-docs/bidders/pubtech.md
Labels: LGTM

#4617 Remove duplicate sidebarType meta tag for districtm
  dev-docs/bidders/districtm.md
Labels: bug

#4616 Remove duplicate gvl_id for browsi
  dev-docs/bidders/browsi.md
Labels: bug

#4638 Release notes for Prebid 8
  dev-docs/pb8-notes.md
  dev-docs/release-notes.md
Labels: Pending Next Major Release

#4641 JS: update docs on activity controls
  dev-docs/activity-controls.md
  dev-docs/modules/allowActivities.md
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM, Pending Next Major Release

#4286 Renamed cpexId to czechAdId
  dev-docs/modules/userId.md
  dev-docs/modules/userid-submodules/cpexid.md
Labels: LGTM, Pending Next Major Release

#4528 Renaming TrustPid User ID module to Utiq
  dev-docs/modules/userid-submodules/utiq.md
Labels: LGTM, Pending Next Major Release

#4490 add retailspot documentation
  dev-docs/bidders/retailspot.md
Labels: needs work, not merged yet

#4634 Update KiviAds adapter - add Prebid.js support
  dev-docs/bidders/kiviads.md
Labels: LGTM, not merged yet

#4618 Remove duplicate fpd_support for openx
  dev-docs/bidders/openx.md
Labels: bug

#4615 remove duplicate meta tag for brave
  dev-docs/bidders/brave.md
Labels: bug

#4610 New adapter - MgidX
  dev-docs/bidders/mgidX.md
Labels: LGTM, not merged yet

#4495 Add FreePass BidAdapter docs
  dev-docs/bidders/freepass.md
Labels: LGTM, not merged yet

#4482 New adapter: Brid
  dev-docs/bidders/brid.md
Labels: LGTM, not merged yet

#4630 Update floors.md - 4 rule sets
  dev-docs/modules/floors.md
Labels: needs work
