Repository prebid/prebid.github.io, pull requests merged in 2024-01, with the labels that each got.

#4995 Update PrebidJS Description
  dev-docs/bidders/tpmn.md
Labels: LGTM

#4702 renamed idWardRtdProvider to anonymisedRtdProvider
  dev-docs/modules/anonymisedRtdProvider.md
  dev-docs/modules/idWardRtdProvider.md
Labels: LGTM, not merged yet

#5031 PBS docs updates for PBS-Java 2.5
  prebid-server/developers/add-new-bidder-java.md
  prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
Labels: LGTM

#5040 MyGaru Id System: initial release
  dev-docs/modules/userid-submodules/mygaru.md
Labels: LGTM, not merged yet

#5055 Ampliffy Bid Adapter Documentation
  dev-docs/bidders/ampliffy.md
Labels: not merged yet

#5044 Admixer Bid Adaper: add admixerwl alias
  dev-docs/bidders/admixerwl.md
Labels: needs work, Pending PBJS Release

#5010 update greenbids modules documentation
  dev-docs/analytics/greenbids.md
  dev-docs/modules/greenbidsRtdProvider.md
Labels: LGTM, not merged yet

#4970 New adapter: r2b2
  dev-docs/bidders/r2b2.md
Labels: LGTM, not merged yet

#4931 relevantDigital: Add pbs documentation
  dev-docs/bidders/relevantdigital.md
Labels: LGTM

#5054 Ad2iction Bid Adapter: initial release
  dev-docs/bidders/ad2iction.md
Labels: not merged yet

#5083 removing PG support
  prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
  prebid-server/endpoints/pbs-endpoint-event.md
  prebid-server/features/pbs-feature-idx.md
  prebid-server/features/pg/pbs-pg-bidder.md
  prebid-server/features/pg/pbs-pg-glossary.md
  prebid-server/features/pg/pbs-pg-host.md
  prebid-server/features/pg/pbs-pg-idx.md
  prebid-server/features/pg/pbs-pg-plan.md
  prebid-server/features/pg/pbs-pg-targeting.md
  prebid-server/hosting/pbs-hosting.md
  prebid-server/versions/pbs-versions-java.md
  prebid/pg.md
Labels: LGTM

#5076 Updated ix.md
  dev-docs/bidders/ix.md
Labels: LGTM

#5026 Bizzclick: update doc
  dev-docs/bidders/bizzclick.md
Labels: LGTM

#5069 Add adops video overview
  adops/adops-overview-video.md
  adops/adops-planning-guide.md
  adops/overview
  overview/all-videos.md
Labels: LGTM

#5024 dsp_geniee Bid Adapter : add dsp_geniee.md
  dev-docs/bidders/dsp_geniee.md
Labels: LGTM, not merged yet

#5096 ID5 ID Module: ID5 will be able to optionally delegate its logic
  dev-docs/modules/userid-submodules/id5.md
Labels: LGTM

#5081 IQX prebid adapter docs
  dev-docs/bidders/iqx.md
Labels: LGTM

#5080 AJA Bid Adapter: update bidder specification
  dev-docs/bidders/aja.md
Labels: LGTM

#5025 Tagoras bid adapter
  dev-docs/bidders/tagoras.md
Labels: LGTM

#5051 NextMillennium: currency support in request
  dev-docs/bidders/nextMillennium.md
Labels: LGTM

#5098 AdElement Bid Adapter: initial release doc
  dev-docs/bidders/adelement.md
Labels: not merged yet

#5103 Yandex: update adapter docs
  dev-docs/bidders/yandex.md
Labels: LGTM
