Repository prebid/prebid.github.io, pull requests merged in 2024-12, with the labels that each got.

#5756 Yandex Metrica Analytics: updated links to the interface
  dev-docs/analytics/yandex.md
Labels: LGTM

#5740 Aso Bid Adapter: documenting kuantyx alias
  dev-docs/bidders/kuantyx.md
Labels: LGTM

#5749 Adding auctionDelay param to currency module
  dev-docs/modules/currency.md
Labels: LGTM

#5741 Module Execution Config
  prebid-server/pbs-modules/index.md
Labels: LGTM, Pending PBS Release

#5744 Adkernel: updating SpinX alias doc
  dev-docs/bidders/spinx.md
Labels: LGTM

#5714 AdMatic: documenting adt alias
  dev-docs/bidders/adt.md
Labels: needs work, not merged yet

#5737 Adkernel: documenting Pixelpluses alias
  dev-docs/bidders/pixelpluses.md
Labels: LGTM

#5735 Rise: Update bidder docs
  dev-docs/bidders/rise.md
Labels: LGTM, not merged yet

#5734 BeOp Adapter doc: Access storage explained
  dev-docs/bidders/beop.md
Labels: LGTM, not merged yet

#5724 Blue: Add placementId bidder param
  dev-docs/bidders/blue.md
Labels: LGTM, not merged yet

#5701 Intent IQ Analytics Adapter: Support domainName parameter
  dev-docs/modules/userid-submodules/intentiq.md
Labels: LGTM, not merged yet

#5694 nextMillenniumBidAdapter: Added supply chain support
  dev-docs/bidders/nextMillennium.md
Labels: LGTM

#5676 New bid adapter: Adverxo
  dev-docs/bidders/adport.md
  dev-docs/bidders/adverxo.md
  dev-docs/bidders/bidsmind.md
  dev-docs/bidders/mobupps.md
Labels: LGTM, not merged yet

#5663 Epsilon: enable audio
  dev-docs/bidders/epsilon.md
Labels: LGTM, not merged yet

#5635 Adkernel: documenting RxNetwork alias
  dev-docs/bidders/rxnetwork.md
Labels: LGTM, not merged yet

#5595 Update Connatix adapter
  dev-docs/bidders/connatix.md
Labels: LGTM, not merged yet

#5552 Nativo bid adapter documentation updates
  dev-docs/bidders/nativo.md
Labels: LGTM, not merged yet

#5771 Module Configuration Documentation
  prebid-server/developers/add-a-module-java.md
  prebid-server/pbs-modules/greenbids-real-time-data.md
  prebid-server/pbs-modules/index.md
Labels: LGTM

#5571 Insticator: Update doc to support PBS
  dev-docs/bidders/insticator.md
Labels: LGTM, Pending PBS Release

#5763 addStellormedia allias
  dev-docs/bidders/stellormedia.md
Labels: LGTM, not merged yet

#5743 Rediads bid adapter
  dev-docs/bidders/rediads.md
Labels: LGTM, not merged yet

#5751 Mobile: Add section about ad position configuration
  _includes/mobile/adunit-config-android.md
  _includes/mobile/adunit-config-ios.md
  _includes/mobile/rendering-adunit-config-android.md
  _includes/mobile/rendering-adunit-config-ios.md
  prebid-mobile/modules/rendering/android-sdk-integration-admob.md
  prebid-mobile/modules/rendering/android-sdk-integration-gam.md
  prebid-mobile/modules/rendering/android-sdk-integration-max.md
  prebid-mobile/modules/rendering/android-sdk-integration-pb.md
  prebid-mobile/modules/rendering/ios-sdk-integration-admob.md
  prebid-mobile/modules/rendering/ios-sdk-integration-gam.md
  prebid-mobile/modules/rendering/ios-sdk-integration-max.md
  prebid-mobile/modules/rendering/ios-sdk-integration-pb.md
Labels: needs work

#5759 Mobile: update docs for setORTB functions
  _includes/mobile/adunit-config-android.md
  _includes/mobile/adunit-config-ios.md
  prebid-mobile/pbm-api/android/pbm-targeting-android.md
  prebid-mobile/pbm-api/ios/pbm-targeting-ios.md
Labels: LGTM, not merged yet

#5769 Lotame URL & wording updates
  dev-docs/modules/userid-submodules/lotame.md
Labels: needs work
