Repository prebid/prebid.github.io, pull requests merged in 2024-07, with the labels that each got.

#5455 Adnuntius Bid Adaptor: add new advertiserTransparency feature
  dev-docs/bidders/adnuntius.md
Labels: LGTM

#5404 MGIDX Adapter: Update
  dev-docs/bidders/mgidX.md
Labels: LGTM

#5346 Update Vidazoo bidder documentation
  dev-docs/bidders/vidazoo.md
Labels: LGTM, not merged yet

#5323 Update Cointraffic for Prebid-Server support
  dev-docs/bidders/cointraffic.md
Labels: LGTM, not merged yet

#5466 Bizzclick Bid Adapter: remove deprecated params
  dev-docs/bidders/blasto.md
Labels: LGTM

#5468 Openweb adapter: PBS supported
  dev-docs/bidders/openweb.md
Labels: LGTM

#5461 Update documentation
  dev-docs/modules/userid-submodules/intentiq.md
Labels: LGTM

#5193 Update load-cookie documentation
  dev-docs/show-prebid-ads-on-amp-pages.md
  prebid-server/developers/pbs-cookie-sync.md
Labels: on hold

#5426 Copper6SSP: new adapter
  dev-docs/bidders/copper6ssp.md
Labels: LGTM, not merged yet

#5364 Add note for playinline for Teads adapter
  dev-docs/bidders/teads.md
Labels: LGTM, not merged yet

#5265 New adapter MarkApp
  dev-docs/bidders/markapp.md
Labels: needs work

#5109 Smilewanted : add native support
  dev-docs/bidders/smilewanted.md
Labels: needs work

#5470 Admixer Alias: RTB Stack
  dev-docs/bidders/rtbstack.md
Labels: LGTM

#5449 Cee id system documentation
  dev-docs/modules/userid-submodules/ceeIdSystem.md
Labels: LGTM

#5479 add config example
  dev-docs/analytics/intentiq.md
Labels: LGTM, Pending PBJS Release

#5487 Adkernel: documenting voisetech alias
  dev-docs/bidders/voisetech.md
Labels: LGTM

#4920 Utiq ID submodule: Update module name, parameters and contact
  dev-docs/modules/userid-submodules/utiq.md
Labels: Pending Next Major Release

#5480 Update Connatix Docs With Video Media Type Support
  dev-docs/bidders/connatix.md
Labels: LGTM, Pending PBJS Release

#5484 AF-3683 added currencies: CHF and SEK to the documentation
  dev-docs/bidders/visx.md
Labels: LGTM

#5506 Add 1accord Bidder docs
  dev-docs/bidders/1accord.md
Labels: LGTM

#5508 Update documentation on the specific parameters required by the ResetDigital adapter for supported bidders.
  dev-docs/bidders/resetdigital.md
Labels: LGTM

#5456 Update docs per https://github.com/prebid/Prebid.js/pull/11867
  dev-docs/bidders/targetvideo.md
Labels: LGTM

#5414 AzerionEdge RTD Module: Documentation changes
  dev-docs/modules/azerionedgeRtdProvider.md
Labels: LGTM

#5333 51Degrees Prebid Server modules documentation
  prebid-server/pbs-modules/51degrees-device-detection.md
  prebid-server/pbs-modules/index.md
Labels: LGTM

#5503 Ceeid system userId module docs
  dev-docs/modules/userId.md
  dev-docs/modules/userid-submodules/ceeIdSystem.md
Labels: LGTM

#5512 update language to emphasize that mobian module is contextual and not…
  dev-docs/modules/mobianRtdProvider.md
Labels: LGTM

#5473 Create clearAllAuctions.md
  dev-docs/publisher-api-reference/clearAllAuctions.md
Labels: LGTM, not merged yet

#5472 OwnAdX PrebidJS Bidder Docs
  dev-docs/bidders/ownadx.md
Labels: LGTM, not merged yet

#5330 Displayio: add prebid server adapter support
  dev-docs/bidders/displayio.md
Labels: LGTM, not merged yet

#5498 ID5 UserId - no longer requiring html storage type
  dev-docs/modules/userid-submodules/id5.md
Labels: LGTM, not merged yet

#5495 Adagio Analytics Adapter: Add new config options field examples
  dev-docs/analytics/adagio.md
Labels: not merged yet

#5504 kimberliteBidAdapter: video support docs update
  dev-docs/bidders/kimberlite.md
Labels: LGTM, not merged yet
