Repository prebid/prebid.github.io, pull requests merged in 2024-04, with the labels that each got.

#5198 Smrtconnect Bid Adapter: initial release doc
  dev-docs/bidders/smrtconnect.md
Labels: LGTM

#5231 Adkernel: documenting monetix alias
  dev-docs/bidders/monetix.md
Labels: needs work

#5211 Update deepintent docs with gpp and coppa compliance
  dev-docs/bidders/deepintent.md
Labels: LGTM, not merged yet

#5239 Update ix.md
  dev-docs/bidders/ix.md
Labels: needs work

#5162 Opsco Bid Adapter Documentation
  dev-docs/bidders/opsco.md
Labels: LGTM, not merged yet

#5254 JS: update doceree bidder code
  dev-docs/bidders/doceree.md
Labels: LGTM

#5190 [JW Player RTD Module] Updates docs for new content fields and deprecated config param
  dev-docs/modules/jwplayerRtdProvider.md
Labels: LGTM, not merged yet

#5223 Loyal Bid Adapter: initial release
  dev-docs/bidders/loyal.md
Labels: LGTM, not merged yet

#5262 Fixing doceree title
  dev-docs/bidders/doceree.md
Labels: LGTM

#5135 Prebid.js: new PAAPI module documentation
  dev-docs/modules/fledgeForGpt.md
  dev-docs/modules/paapi.md
  dev-docs/publisher-api-reference/getPAAPIConfig.md
  dev-docs/publisher-api-reference/setPAAPIConfigForGPT.md
Labels: not merged yet

#5246 New adapter: emetriq
  dev-docs/bidders/emetriq.md
Labels: LGTM

#5257 AzerionEdge RTD Module: New mandatory parameters
  dev-docs/modules/azerionedgeRtdProvider.md
Labels: LGTM

#5091 Dailymotion Bid Adaptor: initial release
  dev-docs/bidders/dailymotion.md
Labels: LGTM

#5258 Insticator: Update documentation, add third party field support
  dev-docs/bidders/insticator.md
Labels: LGTM

#5275 Optidigital Bid Adapter: Add gpp support
  dev-docs/bidders/optidigital.md
Labels: LGTM

#5199 Anyclip bidder dev doc
  dev-docs/bidders/anyclip.md
Labels: LGTM

#5236 Relaido Bid Adapter: add params for ogUrl
  dev-docs/bidders/relaido.md
Labels: LGTM, not merged yet

#5247 Update OpenWeb Bidder Docs
  dev-docs/bidders/openweb.md
Labels: LGTM
