Repository prebid/prebid.github.io, pull requests merged in 2024-11, with the labels that each got.

#5674 LiveIntent UserId module: Add support for sharethrough, sonobi, vidazoo IDs
  dev-docs/modules/userid-submodules/liveintent.md
Labels: LGTM

#5671 Qortex RTD Provider: update documentation
  dev-docs/modules/qortexRtdProvider.md
Labels: LGTM

#5654 New Bidder:tapnative
  dev-docs/bidders/tapnative.md
  dev-docs/modules/ehealthcaresolutions.md
Labels: LGTM

#5582 Preciso Bid Adapter: update
  dev-docs/bidders/preciso.md
Labels: LGTM

#5672 NextMillenniumBidAdapter: Updated description
  dev-docs/bidders/nextMillennium.md
Labels: LGTM

#5624 Changed Adapter name/description; Added floor support
  dev-docs/bidders/aniview.md
Labels: LGTM

#5607 Contxtful Bidder adapter: New Documentation
  dev-docs/bidders/contxtful.md
Labels: LGTM

#5679 PBS-Go V3 Updates
  prebid-server/developers/add-a-module-go.md
  prebid-server/developers/add-new-bidder-go.md
  prebid-server/endpoints/info/pbs-endpoint-info.md
Labels: LGTM

#5698 Video Module: Dup removal
  prebid-video/video-overview.md
Labels: LGTM

#5696 Equativ bid adapter documentation
  dev-docs/bidders/equativ.md
Labels: LGTM

#5669 IntentIq ID & Analytics Modules: update documentation
  dev-docs/analytics/intentiq.md
  dev-docs/modules/userid-submodules/intentiq.md
Labels: LGTM

#5652 Add Exco bidder documentation
  dev-docs/bidders/exco.md
Labels: LGTM

#5697 Bidmatic adapter: text changes
  dev-docs/bidmatic.md
Labels: LGTM

#5691 Add Easybid Bidder docs
  dev-docs/bidders/easybid.md
Labels: LGTM

#5703 Added The Newco userId module - TNCID documentation
  dev-docs/modules/userid-submodules/tncIdSystem.md
Labels: LGTM

#5693 Hadrn 1004
  dev-docs/modules/userid-submodules/hadron.md
Labels: needs work

#5719 paapi: support for parallel PAAPI and contextual auctions
  dev-docs/modules/paapi.md
Labels: LGTM

#5709 JS: update documentation for markWinningBidAsUsed/renderer
  dev-docs/publisher-api-reference/markWinningBidAsUsed.md
  dev-docs/show-outstream-video-ads.md
Labels: LGTM

#5695 Gamera Rtd Provider: Initial release
  dev-docs/modules/gameraRtdProvider.md
Labels: LGTM

#5686 New Bidder:ehealthcaresolutions
  dev-docs/bidders/ehealthcaresolutions.md
Labels: LGTM

#5660 New User ID submodule: Rewarded Interest
  dev-docs/modules/userId.md
  dev-docs/modules/userid-submodules/rewardedInterest.md
Labels: LGTM

#5613 Greenbids RTD Module
  prebid-server/pbs-modules/greenbids-real-time-data.md
Labels: needs work

#5704 Adkernel: documenting RevBid alias
  dev-docs/bidders/revbid.md
Labels: LGTM, Pending PBJS Release

#5715 Airgrid add Video Support
  dev-docs/bidders/adgrid.md
Labels: LGTM, Pending PBJS Release

#5723 Bidtheatre Bidder Adapter: initial release, docs
  dev-docs/bidders/bidtheatre.md
Labels: LGTM

#5727 Copper6ssp Bid Adapter: add gvl_id
  dev-docs/bidders/copper6ssp.md
Labels: LGTM, Pending PBJS Release

#5572 teads.md: add disclosure
  _includes/dev-docs/fingerprinting.md
  dev-docs/bidders/teads.md
Labels: question, LGTM

#5700 PgamSSP Bid Adapter: add endpointId parameter to doc
  dev-docs/bidders/pgamssp.md
Labels: needs work
