Repository prebid/prebid.github.io, pull requests merged in 2024-05, with the labels that each got.

#5291 STN Bid Adapter: Remove Multi Currency Support
  dev-docs/bidders/stn.md
Labels: LGTM

#5290 MinuteMedia Bid Adapter: Remove Multi Currency Support
  dev-docs/bidders/minutemedia.md
Labels: LGTM

#5272 optable: Add documentation
  dev-docs/bidders/optable.md
Labels: LGTM

#5256 [New Bid Adapter] JW Player Bid Adapter
  dev-docs/bidders/jwplayer.md
Labels: LGTM

#5289 Rise Bid Adapter: Remove Multi Currency Support
  dev-docs/bidders/rise.md
  dev-docs/bidders/risexchange.md
Labels: LGTM

#5242 Update readpeak docs
  dev-docs/bidders/readpeak.md
Labels: LGTM

#5292 lmpIdSystem: Add initial documentation
  dev-docs/modules/userid-submodules/lmpid.md
Labels: LGTM

#5299 [Criteo] Documentation pubid on Criteo Prebid Docs
  dev-docs/bidders/criteo.md
Labels: LGTM

#5300 Update theAdx.md
  dev-docs/bidders/theAdx.md
Labels: LGTM

#5306 EXADS adapter - Changed bidder code
  dev-docs/bidders/exads.md
Labels: LGTM

#5301 removed adomik from the list of partners (app sunsetted)
  _data/partners.yml
  assets/images/partners/community/Adomik-logo.png
  dev-docs/analytics/adomik.md
Labels: Pending Next Major Release

#5274 Playdigo: new adapter
  dev-docs/bidders/playdigo.md
Labels: LGTM

#5270 UtiqMTPId doc: adding documentation for the new UtiqMTPId user id submodule
  dev-docs/modules/userId.md
  dev-docs/modules/userid-submodules/utiqMtp.md
Labels: LGTM

#5267 Added docs for Twist Digital bid adapter
  dev-docs/bidders/twistDigital.md
Labels: LGTM

#5230 eight pod init
  dev-docs/analytics/eightPod.md
  dev-docs/bidders/eightPod.md
Labels: LGTM, Pending PBJS Release

#5259 performax bidder
  dev-docs/bidders/performax.md
Labels: LGTM

#5310 Dailymotion Prebid Adapter: documentation update
  dev-docs/bidders/dailymotion.md
Labels: LGTM

#5317 Fix Algorix and Rixengine
  dev-docs/bidders/algorix.md
  dev-docs/bidders/rixengine.md
Labels: LGTM

#5266 glossary update
  overview/glossary.md
Labels: LGTM

#5314 Corrected link address in the idWardRtdProvider.md
  dev-docs/modules/idWardRtdProvider.md
Labels: LGTM

#5320 AcuityAds adapter: update filename
  dev-docs/bidders/acuityads.md
Labels: LGTM

#5315 User ID: Ability to store user IDs in cookie and localStorage simultaneously
  dev-docs/modules/userId.md
Labels: LGTM

#5321 Seedtag Bid Adapter: updates ortb blocking supported to partial
  dev-docs/bidders/seedtag.md
Labels: LGTM

#5318 AdsYield Bid Adapter: move to limelight
  dev-docs/bidders/adsyield.md
Labels: LGTM

#5327 Adzymic Bid Adapter: Add new IAB GVL Id
  dev-docs/adzymic.md
Labels: LGTM

#5325 added documentation on how to disable cstg flag if needed
  dev-docs/modules/userid-submodules/euid.md
  dev-docs/modules/userid-submodules/unified2.md
Labels: LGTM

#5341 Moved adzymic.md to bidders subfolder and corrected TCF value to true
  dev-docs/bidders/adzymic.md
Labels: LGTM

#5338 support-dchain
  dev-docs/bidders/taboola.md
Labels: LGTM

#5336 Update Teads documentation for supported GPP privacy laws
  dev-docs/bidders/teads.md
Labels: LGTM

#5352 Welect Bid Adapter: re-add adapter to docs
  dev-docs/bidders/welect.md
Labels: LGTM

#5335 Interaction with `ActivityInfrastructure` for modules
  prebid-server/developers/add-a-module-java.md
Labels: LGTM

#5337 Adkernel: documenting hyperbrainz alias
  dev-docs/bidders/hyperbrainz.md
Labels: LGTM

#5344 IQzone: Adapter update
  dev-docs/bidders/iqzone.md
Labels: LGTM

#5362 Lucead bid adapter: Update
  dev-docs/bidders/adliveplus.md
  dev-docs/bidders/lucead.md
Labels: LGTM

#5316 medianet Paapi support
  dev-docs/bidders/medianet.md
Labels: LGTM

#5322 Contxtful RTD Provider - Updated Documentation
  dev-docs/modules/contxtfulRtdProvider.md
Labels: LGTM, not merged yet

#5340 Update Beachfront doc for plcmt
  dev-docs/bidders/beachfront.md
Labels: LGTM, Pending PBJS Release

#5351 Adagio Rtd Provider: add doc
  dev-docs/modules/adagioRtdProvider.md
Labels: LGTM, not merged yet

#5302 add driftpixel Adapter
  dev-docs/bidders/driftpixel.md
Labels: LGTM

#5307 Insticator Bid Adaptor: update docs for bidfloor
  dev-docs/bidders/insticator.md
Labels: LGTM

#5312 Feature/colombia bid adapter
  dev-docs/bidders/colombia.md
Labels: needs work

#5287 51Degrees module documentation: initial commit
  dev-docs/modules/51DegreesRtdProvider.md
Labels: LGTM
