Repository prebid/prebid.github.io, pull requests merged in 2024-08, with the labels that each got.

#5522 QT Adapter: pbs set to true
  dev-docs/bidders/qt.md
Labels: LGTM

#5518 + onAdRenderSucceeded
  dev-docs/bidder-adaptor.md
Labels: LGTM

#5407 TheTradeDesk documentation
  dev-docs/bidders/ttd.md
Labels: LGTM, not merged yet

#5397 AdvRed analytics adapter
  dev-docs/analytics/advRed.md
Labels: Pending PBJS Release

#5538 update configuration example
  dev-docs/modules/userid-submodules/intentiq.md
Labels: LGTM

#5536 AdvRed Analytics Adapter: update documentation css
  dev-docs/analytics/advRed.md
Labels: LGTM

#5534 Dailymotion bid adapter: Add player name
  dev-docs/bidders/dailymotion.md
Labels: LGTM

#5531 Mediago : remove outdated note on download page
  dev-docs/bidders/mediago.md
Labels: LGTM

#5528 Pstudio: Change prebid body request param
  dev-docs/bidders/pstudio.md
Labels: LGTM

#5516 refresh timeout, setConfig pages
  assets/images/dev-docs/prebid-timeouts.png
  dev-docs/publisher-api-reference/setConfig.md
  features/timeouts.md
Labels: LGTM

#5474 add VimayX adapter
  dev-docs/bidders/vimayx.md
Labels: LGTM

#5438 New Adapter: Filmzie
  dev-docs/bidders/filmzie.md
Labels: LGTM

#5421 MetaX Documentation
  dev-docs/bidders/metax.md
Labels: LGTM

#5535 New bidder adapter: TGM
  dev-docs/bidders/tgm.md
Labels: LGTM

#5526 paapi gtpt module verbiage update
  dev-docs/modules/fledgeForGpt.md
Labels: LGTM

#5521 New adapter FelixAds
  dev-docs/bidders/felixads.md
Labels: LGTM

#5520 Pubrise: new adapter
  dev-docs/bidders/pubrise.md
Labels: LGTM

#5527 EClickAds: new bid adapter docs
  dev-docs/bidders/eclickads.md
Labels: needs work

#5525 Add targetVideoAdServer docs
  dev-docs/publisher-api-reference/adServers.targetVideo.buildVideoUrl.md
Labels: LGTM, Pending PBJS Release

#5546 New bidder Adapter - MediaConsortium
  dev-docs/bidders/mediaConsortium.md
Labels: LGTM, Pending PBJS Release

#5541 New bidder Adapter - djaxBidAdapter
  dev-docs/bidders/djax.md
Labels: LGTM, Pending PBJS Release

#5490 Add description of PBS Greenbids Analytics Reporter
  prebid-server/pbs-modules/greenbids-analytics-reporter.md
Labels: LGTM, Pending PBS Release

#5537 Update table of collected FPD data
  features/firstPartyData.md
Labels: LGTM, not merged yet

#5517 51d: update go module id and paths to flatcase
  prebid-server/pbs-modules/51degrees-device-detection.md
Labels: LGTM, not merged yet

#5483 Taboola: pbs support app
  dev-docs/bidders/taboola.md
Labels: LGTM

#5560 New Adapter: Freedom Ad Network Bidder Adapter
  dev-docs/bidders/freedomadnetwork.md
Labels: needs work, Pending PBJS Release

#5551 ssp_geniee Bid Adapter : add ssp_geniee.md
  dev-docs/bidders/ssp_geniee.md
Labels: needs work, not merged yet
