Repository prebid/prebid.github.io, pull requests merged in 2025-07, with the labels that each got.

#6122 Equativ Bid Adapter: adding integration examples
  dev-docs/bidders/equativ.md
Labels: LGTM

#6119 relevatehealth : removed user_id compulsion and used common library
  dev-docs/bidders/relevatehealth.md
Labels: LGTM

#6030 adding documentation for jixie Id module which is applying for submission into the PrebidJs repo concurrently
  dev-docs/modules/userid-submodules/jixie.md
Labels: LGTM

#6101 Zeta SSP Adapter: add GPP support.
  dev-docs/bidders/zeta_global_ssp.md
Labels: LGTM

#6113 Prebid 10 release notes
  dev-docs/pb10-notes.md
  dev-docs/release-notes.md
Labels: LGTM

#6143 add text on UtiqMtp ID configuration, add row on table for bidders
  dev-docs/modules/userid-submodules/utiqMtp.md
Labels: LGTM

#6125 humansecurityMalvDefense Rtd Provider: replacement for cleanioRtdProvider
  dev-docs/modules/cleanioRtdProvider.md
  dev-docs/modules/humansecurityMalvDefenseRtdProvider.md
Labels: needs work

#6144 Add theads alias to admixer
  dev-docs/bidders/theads.md
Labels: LGTM

#6134 T Advertising Solutions Bid Adapter: initial release
  dev-docs/bidders/tadvertising.md
Labels: LGTM, Pending PBJS Release

#6180 Updated Multi Format Support field
  dev-docs/bidders/onetag.md
Labels: LGTM

#6176 New adapter: newdream
  dev-docs/bidders/newdream.md
Labels: needs work

#6136 Docs/update missena params
  dev-docs/bidders/missena.md
Labels: LGTM
