Repository prebid/prebid.github.io, pull requests merged in 2025-04, with the labels that each got.

#5963 Equativ Bid Adapter: fixing compatibilities
  dev-docs/bidders/equativ.md
Labels: LGTM

#5973 symitriDapRTDProvider - Update docs to handle cases where no identity…
  dev-docs/modules/symitriDapRtdProvider.md
Labels: LGTM

#5952 StackAdapt Bid Adapter: initial release
  dev-docs/bidders/stackadapt.md
Labels: LGTM, Pending PBJS Release, not merged yet

#5930 New RTD submodule: optableRtdProvider
  dev-docs/modules/optableRtdProvider.md
Labels: LGTM, Pending PBJS Release

#5950 Adgrid new param placement
  dev-docs/bidders/adgrid.md
Labels: needs work

#5960 Mobile: Support SKAdNetwork and SKOverlay in Bidding-only scenario
  _includes/mobile/adunit-config-ios.md
Labels: LGTM, Pending Prebid Mobile Release

#5889 Mobile: Track `burl` and `nurl` in Rendering API
  _includes/mobile/intro-admob.md
  _includes/mobile/intro-applovin.md
  _includes/mobile/intro-prebid-rendered.md
  assets/images/prebid-mobile/mobile-details-gam-prebid-rendered.png
Labels: LGTM

#5986 Fix typo in renderer.md
  dev-docs/renderer.md
Labels: LGTM

#5956 MediaEyes Bid Adapter: initial release
  dev-docs/bidders/mediaeyes.md
Labels: LGTM, Pending PBJS Release, not merged yet

#5912 Dochase Bid Adapter : Initial Release
  dev-docs/bidders/dochase.md
Labels: LGTM

#5992 InMobi : Update inmobi.md for optional parameters addition
  dev-docs/bidders/inmobi.md
Labels: LGTM

#5990 updated prev auct info docs to include the new highestBidCurrency field
  dev-docs/modules/previousAuctionInfo.md
Labels: LGTM

#5870 IIon adapter, update TCF flag
  dev-docs/bidders/iionads.md
Labels: LGTM, Pending PBJS Release

#5944 add adipolo Adapter
  dev-docs/bidders/adipolo.md
Labels: LGTM, Pending PBJS Release

#5959 Add documentation for targetingControl.allBidsCustomTargeting
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM, Pending PBJS Release, not merged yet

#6006 Nativo: Fix Documentation
  dev-docs/bidders/nativo.md
Labels: LGTM

#5934 mobkoi: add pbs support
  dev-docs/bidders/mobkoi.md
Labels: LGTM

#5923 raveltechRtdProvider: Initial documentation release
  dev-docs/modules/raveltechRtdProvider.md
Labels: not merged yet

#5918 Vistars bid adapter
  dev-docs/bidders/vistars.md
Labels: LGTM, not merged yet

#5905 RobustaBidAdapter: docs
  dev-docs/bidders/robusta.md
Labels: LGTM

#5880 Add documentation for new limelight aliases
  dev-docs/bidders/adtarget_org.md
  dev-docs/bidders/orangeclickmedia.md
  dev-docs/bidders/streamvision.md
  dev-docs/bidders/velonium.md
Labels: LGTM

#5883 Added documentation for epomDspBidAdapter
  dev-docs/bidders/epomDspBidAdapter.md
Labels: LGTM, not merged yet

#5915 Update for pixfuture.md
  dev-docs/bidders/pixfuture.md
Labels: LGTM, not merged yet, Pending PBS Release
