Repository prebid/prebid.github.io, pull requests merged in 2025-09, with the labels that each got.

#6114 Added and updated AdPlus docs
  dev-docs/analytics/adplus.md
  dev-docs/bidders/adplus.md
  dev-docs/modules/userid-submodules/adplus.md
Labels: LGTM, Pending PBJS Release, not merged yet

#6009 Adverxo Bid Adapter: Remove Mobupps as alias
  dev-docs/bidders/mobupps.md
Labels: LGTM, Pending Next Major Release

#5991 AdOcean Adapter: Removed
  dev-docs/bidders/adocean.md
Labels: LGTM, not merged yet, Pending PBS Release, Pending Next Major Release

#6236 Valuad Bid Adapter: Update tcf support
  dev-docs/bidders/valuad.md
Labels: LGTM, Pending PBJS Release

#6246 IntentIq ID & Analytics Modules: Client Hints timeout documentation
  dev-docs/modules/userid-submodules/intentiq.md
Labels: LGTM

#6250 Fix typo in userId.md
  dev-docs/modules/userId.md
Labels: LGTM

#6249 Update intentiq.md
  dev-docs/modules/userid-submodules/intentiq.md
Labels: LGTM
