Repository prebid/prebid.github.io, pull requests merged in 2025-03, with the labels that each got.

#5731 New Bidder: Michao
  dev-docs/bidders/michao.md
Labels: LGTM, Pending PBJS Release

#5836 Attekmi: add Addigi adapter
  dev-docs/bidders/addigi.md
Labels: LGTM

#5752 Mobile: Update plugin renderer section
  prebid-mobile/pbm-api/ios/pbm-plugin-renderer.md
Labels: LGTM, not merged yet

#5810 feat: Add BMS documentation
  dev-docs/bidders/bms.md
Labels: Pending PBJS Release

#5830 OMS: added video support
  dev-docs/bidders/oms.md
Labels: LGTM

#5840 JS: update docs on `eventtrackers` and `markWinningBidAsUsed`
  dev-docs/bidder-adaptor.md
  dev-docs/publisher-api-reference/markWinningBidAsUsed.md
Labels: LGTM

#5842 updated vdo.ai bidder adapter documentation according to the new server
  dev-docs/bidders/vdoai.md
Labels: LGTM

#5858 Bidtheatre Bidder Adapter: pbs support
  dev-docs/bidders/bidtheatre.md
Labels: LGTM

#5864 add permutiveIdentityManagerIdSystem docs
  dev-docs/modules/userid-submodules/permutiveIdentityManagerIdSystem.md
Labels: LGTM, Pending PBJS Release

#5866 Seedtag Bidder Adapter: pbs support
  dev-docs/bidders/seedtag.md
Labels: LGTM

#5891 Dailymotion bid adapter: add ortb converter and floor price support
  dev-docs/bidders/dailymotion.md
Labels: LGTM

#5827 Create overtoneRtdProvider.md
  dev-docs/modules/overtoneRtdProvider.md
Labels: LGTM

#5913 Artechnology: add PBS support
  dev-docs/bidders/artechnology.md
Labels: LGTM

#5916 Aniview: Add examples and update params list
  dev-docs/bidders/aniview.md
Labels: needs work

#5926 feat(): EXCO Bid Adapter: Support of new publisherId, accountId and tagId parameters.
  dev-docs/bidders/exco.md
Labels: LGTM

#5949 Update adgeneration doc add first party data
  dev-docs/bidders/adgeneration.md
Labels: LGTM

#5896 CEE Id System: Added functionality to request endpoint for ID - documentation
  dev-docs/modules/userid-submodules/ceeIdSystem.md
Labels: LGTM

#5955 Fix schain documentation tentatively
  dev-docs/show-prebid-ads-on-amp-pages.md
  prebid-server/developers/add-new-bidder-go.md
  prebid-server/developers/add-new-bidder-java.md
  prebid-server/endpoints/openrtb2/auction-request-example.md
  prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
  prebid-server/features/pbs-feature-idx.md
Labels: LGTM

#5936 Update onetag.md
  dev-docs/bidders/onetag.md
Labels: LGTM, Pending PBJS Release, not merged yet

#5873 Mobile: Support Native Impression Tracking
  _includes/mobile/adunit-config-android.md
  _includes/mobile/adunit-config-ios.md
Labels: Pending Prebid Mobile Release

#5947 Add local way of caching VAST XML
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM

#5929 UNIQUEST Bid Adapter: initial release
  dev-docs/analytics/uniquest.md
  dev-docs/bidders/uniquest.md
Labels: LGTM

#5932 Epsilon: add native support
  dev-docs/bidders/epsilon.md
Labels: LGTM

#5948 disable download on illumin adapter
  dev-docs/bidders/illumin.md
Labels: LGTM

#5785 PAIR: adds TechLab version documentation
  dev-docs/modules/userid-submodules/open-pair.md
Labels: LGTM

#5860 PubMatic RTD Documentation and link added
  dev-docs/modules/pubmaticRtdProvider.md
Labels: Pending PBJS Release, not merged yet
