Repository prebid/prebid.github.io, pull requests merged in 2025-02, with the labels that each got.

#5850 External user id documentation for mobile platforms
  prebid-mobile/pbm-api/android/pbm-targeting-android.md
  prebid-mobile/pbm-api/ios/pbm-targeting-ios.md
Labels: LGTM, Needs second review

#5845 Adkernel: actualizing bidder/aliases documentation
  dev-docs/bidders/adbite.md
  dev-docs/bidders/adkernel.md
  dev-docs/bidders/adomega.md
  dev-docs/bidders/adpluto.md
  dev-docs/bidders/adsolut.md
  dev-docs/bidders/audiencemedia.md
  dev-docs/bidders/bcm.md
  dev-docs/bidders/bidbuddy.md
  dev-docs/bidders/converge.md
  dev-docs/bidders/denakop.md
  dev-docs/bidders/didnadisplay.md
  dev-docs/bidders/digiad.md
  dev-docs/bidders/displayioads.md
  dev-docs/bidders/engageadx.md
  dev-docs/bidders/ergadx.md
  dev-docs/bidders/global_sun.md
  dev-docs/bidders/headbidder.md
  dev-docs/bidders/houseofpubs.md
  dev-docs/bidders/hyperbrainz.md
  dev-docs/bidders/monetix.md
  dev-docs/bidders/motionspots.md
  dev-docs/bidders/oppamedia.md
  dev-docs/bidders/pixelpluses.md
  dev-docs/bidders/qortex.md
  dev-docs/bidders/revbid.md
  dev-docs/bidders/rtbanalytica.md
  dev-docs/bidders/rtbdemand_com.md
  dev-docs/bidders/rxnetwork.md
  dev-docs/bidders/sonic_twist.md
  dev-docs/bidders/spinx.md
  dev-docs/bidders/turktelekom.md
  dev-docs/bidders/unibots.md
  dev-docs/bidders/urekamedia.md
  dev-docs/bidders/voisetech.md
  dev-docs/bidders/waardex_ak.md
Labels: LGTM

#5817 New adapter docs: Connektai
  dev-docs/bidders/connektai.md
Labels: LGTM

#5796 Update conceptx.md with gvlId
  dev-docs/bidders/conceptx.md
Labels: LGTM, Pending PBJS Release

#5794 New Bidder: TradPlus
  dev-docs/bidders/tradplus.md
Labels: LGTM, not merged yet

#5732 Ads Interactive: upd doc
  dev-docs/bidders/ads_interactive.md
Labels: LGTM, not merged yet

#5689 Add new adapter - Brainx
  dev-docs/bidders/brainx.md
Labels: LGTM, not merged yet

#5587 Extend Kobler adapter with prebid-server
  dev-docs/bidders/kobler.md
Labels: LGTM, not merged yet

#5441 gpp support true
  dev-docs/bidders/smartyads.md
Labels: LGTM

#5812 Nodals AI RTD module documentation
  dev-docs/modules/nodalsAiRtdProvider.md
Labels: LGTM, not merged yet

#5865 Criteo bid adapter: update uid type
  dev-docs/bidders/criteo.md
Labels: LGTM

#5811 Smoot Adapter: pbs set to true
  dev-docs/bidders/smoot.md
Labels: LGTM, not merged yet

#5882 update AdGeneration Doc: delete novatiq
  dev-docs/bidders/adgeneration.md
Labels: LGTM

#5884 RTB House: updated feature list
  dev-docs/bidders/rtbhouse.md
Labels: LGTM

#5885 LiveIntent ID Module:: Add docs for zetassp and triplelift
  dev-docs/modules/userid-submodules/liveintent.md
Labels: LGTM

#5834 Greenbids RTD: Account config docs
  prebid-server/pbs-modules/greenbids-analytics-reporter.md
  prebid-server/pbs-modules/greenbids-real-time-data.md
Labels: LGTM

#5899 Add-disclosures-to-guide
  guide.md
Labels: LGTM

#5901 JS: prerendering settings
  dev-docs/publisher-api-reference/setConfig.md
Labels: LGTM

#5902 Add an in-renderer example to the sidebar
  _data/sidebar.yml
  dev-docs/examples/multi-format-example.md
Labels: LGTM

#5818 Add CondorX Bidder docs
  dev-docs/bidders/condorx.md
Labels: LGTM, not merged yet

#5895 Improve Digital Bid Adapter Documentation: MultiBid Support
  dev-docs/bidders/improvedigital.md
Labels: LGTM, Pending PBJS Release, not merged yet

#5892 IntentIq ID & Analytics Modules: GAM reporting documentation
  dev-docs/modules/userid-submodules/intentiq.md
Labels: LGTM, Pending PBJS Release

#5890 ID5 UserId - added docs for canCookieSync param
  dev-docs/modules/userid-submodules/id5.md
Labels: LGTM, Pending PBJS Release

#5904 SemantIQ RTD Provider: initial release
  dev-docs/modules/semantiqRtdProvider.md
Labels: LGTM

#5809 Mobkoi Bidder Adapter and Mobkoi Analytics Adapter initial docs
  dev-docs/analytics/mobkoi.md
  dev-docs/bidders/mobkoi.md
  dev-docs/modules/userid-submodules/mobkoi.md
Labels: LGTM, not merged yet

#5855 Aso Bid Adapter: documenting cordless alias
  dev-docs/bidders/cordless.md
Labels: LGTM, Pending PBJS Release

#5822 Attekmi: add new adapter Adinify
  dev-docs/bidders/adinify.md
Labels: Pending PBJS Release
